### ISSUE TITLE
Autofill Issue on verbal-learning

### ISSUE THREAD

**Issue by DavidPWalsh** [EmotionCognitionLab/pvs#108]
Once you do the audio task (in which it asks you to remember a series of words) at least one time around, when you click on the text box autofill options will appear showing the words that you had previously submitted.

This was seen on a PC using Google Chrome.

**Comment by choipaul92** [comment]
This issue is also found on Microsoft Edge Explorer on Windows

**Comment by Floozutter** [comment]
Good catch! #136 should fix this issue. Please verify that the verbal-learning recall trials no longer autofill on your browsers if you have the chance, once the changes are up.

**Comment by noah10** [comment]
#136 is up and ready for testing.
