### ISSUE TITLE
Daily Stressors - the first question should be aligned to left

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#109]
The first question "what do you feel your stress level is today on a scale from 1 to 9" was centered but the rest of the questions was aligned to left, I think.

Could you align the first question to left as well?

**Comment by noah10** [comment]
The simple way of doing that will cause the 1 to 9 scale to become vertical, taking up a lot of screen real estate. Is that OK? If it's not OK, is this important enough to spend extra effort on left-aligning the question but keeping the 1 to 9 scale horizontal?

**Comment by nashiro** [comment]
I see your point. No, it's not that important. Please disregard my request.
