### ISSUE TITLE
Add "Press 'esc' to exit full screen mode" to the congratulations screen 

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#110]
At the end of the daily tasks, you say "Congratulations! You have done all of the daily measurements for today. Please come back tomorrow to continue."

Could we add, "Press 'esc' to exit full screen mode" at the end?

**Comment by noah10** [comment]
This should now be fixed. Please do a shift-reload to be sure that you're seeing the latest version and close this issue if everything is as requested.

**Comment by nashiro** [comment]
I saw "Press 'esc' to exit full screen mode" at the end of today's daily tasks. Thank you.
