### ISSUE TITLE
access to daily tasks

### ISSUE THREAD

**Issue by sle0207** [EmotionCognitionLab/pvs#111]
When running daily tasks, all Chrome, Firefox, Safari show a blank screen. I used Shift+reload and cleared cache, but it still returns with a blank screen. Same goes for the incognito/private windows. In the console, I get the following messages: 
"Failed to load resource: the server responded with a status /favicon.ico:1 of 403 ()
Uncaught (in promise) TypeError: daily-tasks.aed9ad65...6054c62.bundle.js:1
Cannot read properties of undefined (reading 'dateTime')
      at daily-tasks.aed9ad65d87136054c62.bundle.js:1
    at daily-tasks.aed9ad65d87136054c62.bundle.js:1
    at St (daily-tasks.aed9ad65d87136054c62.bundle.js:1)
    at ze (daily-tasks.aed9ad65d87136054c62.bundle.js:1)
    at Object.Lt [as onSuccess] (daily-tasks.aed9ad65d87136054c62.bundle.js:1)"

**Comment by noah10** [comment]
@sle0207  - Please use the project slack channel to let me know what email address you registered with and I'll take a look at this.

**Comment by noah10** [comment]
This happened when trying to do the full set of daily tasks after doing individual tasks, which isn't supported. Closing.
