### ISSUE TITLE
N-back task

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#115]
Would it be possible to not have the countdown after the last block? If this is a big hassle to fix, don't worry about it.

**Comment by noah10** [comment]
This is deployed and ready for testing.

**Comment by maramather** [comment]
Hi Paul, that is fine - it is just a question of whether the countdowns appear after the end of the last block.

**Comment by choipaul92** [comment]
Just checked, the countdown does not appear after the end of the last block!

**Comment by noah10** [comment]
Great - I'll close this, then.
