### ISSUE TITLE
Phsyical Activity Survey

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#116]
Could you make the following changes (also shown in the attached screenshot)?

1) Change the instructions to "Please give yourself the appropriate physical activity rating score (0–7) based on the following scale"

2) Remove 1. 2. 3.

3) Add "0 point"  "1 point"  "2 points" ... "7 points" in front of each sentence

![physical activity](https://user-images.githubusercontent.com/26439818/141354291-11682301-75dc-4e3e-b118-9dea2b81ad24.png)

**Comment by noah10** [comment]
I don't think we want the points here - that's something that the computer should be doing, not the user. Having the points there only makes sense if this is on paper; it eases the data entry requirements in that context but introduces confusion and the possibility of error when we move it to the computer. I can remove the 1, 2, 3 easily enough, though.

**Comment by nashiro** [comment]
Ok, I think it is ok not to add points. But yes please remove the 1, 2, 3.

Could you then change the instructions to:
"Please select the sentence that best describes your physical activity level"

@maramather - please let us know if this change in the instructions looks ok.

**Comment by noah10** [comment]
This should now be done. As usual, please shift + reload to make sure you have the latest version.

**Comment by nashiro** [comment]
Tested. It looks good - thank you.
