### ISSUE TITLE
Demographics: last menstrual cycle question

### ISSUE THREAD

**Issue by ycazaherrera** [EmotionCognitionLab/pvs#117]
Change response format from open ended to multiple choice with the below options:

1-2 years
3-6 years
7-10 years
">10 years" - this one doesn't need quotations around it in the demographics form. I used them here so Github wouldn't change the line to what I believe is a code block(?).

**Comment by noah10** [comment]
Do we need a <1 year option?

**Comment by ycazaherrera** [comment]
No. Enrollment is limited to postmenopausal women (at least 12 months since last menses).

**Comment by noah10** [comment]
This should now be fixed. Please do a shift-reload to be sure that you're seeing the latest version and close this issue if everything is as requested.
