### ISSUE TITLE
Demographic information text change

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#122]
Per @nashiro, please add "(including coronary artery disease, angina, and arrhythmia)" after "Heart disease" in the "Are you currently under a doctor’s care for any of the following?" section of the demographic information.

**Comment by noah10** [comment]
This should now be done. Please be sure to shift+reload before testing to ensure you have the latest version.

**Comment by nashiro** [comment]
They look good. Thank you.
