### ISSUE TITLE
Demographic information: Force user to affirm they are not under doctor's care, taking meds

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#123]
Per @nashiro, please add "None of them" as an option under the "Are you currently under a doctor’s care for any of the following?" and "Are you currently taking any medications/drugs" sections and force the user to choose at least one of the available responses in each of those sections.

**Comment by noah10** [comment]
This should now be complete. Please be sure to shift+reload before testing to make sure you have the latest version.

**Comment by nashiro** [comment]
Could you change None to "None of them" for "Are you currently taking any medications/drugs" section?

**Comment by noah10** [comment]
Done. As usual, be sure to shift + reload if you don't see the change, just to be sure you have the most recent version.

**Comment by nashiro** [comment]
Looks good!  Thank you.
