### ISSUE TITLE
N-back: change cue advancement method prior to each trial

### ISSUE THREAD

**Issue by ycazaherrera** [EmotionCognitionLab/pvs#124]
We currently show participants the zero-back, one-back, or two-back cues for 3 seconds at the beginning of the respective trial. We would like to change this screen from timed to an interactive screen where participants press the corresponding number (0, 1, or 2) to indicate that they understand what trial is about to start. The upcoming trial would start once they press the correct number. I will update the specs doc to reflect the wording changes for the corresponding screens.

**Comment by ycazaherrera** [comment]
Specs doc has been updated. Changes are highlighted in yellow.

**Comment by noah10** [comment]
This is ready to be tested.

**Comment by ycazaherrera** [comment]
looks great. thank you!
