### ISSUE TITLE
Background color is white after scrolling down

### ISSUE THREAD

**Issue by ycazaherrera** [EmotionCognitionLab/pvs#126]
On multiple questionnaires, the beige background color would change to white once scrolling past the portion of the questionnaire visible when the page first loads. Screenshot attached.
<img width="2560" alt="background-color" src="https://user-images.githubusercontent.com/82192734/141839495-31e4798a-8908-4c05-959b-8d5c52db9276.png">

**Comment by noah10** [comment]
In #43 it was reported that this happens in safari on macOS Big Sur Version 11.6 in full screen mode, and it only switches back to beige when scrolling back up to what was originally shown on the full screen. This does not happen in Firefox or Chrome on OS X 10.13.6.

**Comment by noah10** [comment]
Closing this as there have been no further reports of it happening.
