### ISSUE TITLE
face-name - repeats one face with two names

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#129]
![Screen Shot 2021-11-16 at 2 31 00 PM](https://user-images.githubusercontent.com/82665055/142077032-536a91e1-0219-4536-af3d-c37303f5e9d4.png)
![Screen Shot 2021-11-16 at 2 31 56 PM](https://user-images.githubusercontent.com/82665055/142077040-881d8427-0c54-41dc-8e86-84725bb45aaa.png)

This woman's face was first shown as "Susan" then in another day's session, as "Jennifer". The test today had her twice, once for each name.

**Comment by nashiro** [comment]
I looked into this. This was an error in the list of stimuli that RA created (EMWfemale18-2neutral.bmp was used for Set 4 & 5 by mistake).  @noah10, I'll let you know once I correct this error.

**Comment by nashiro** [comment]
I changed Set 5 item #2 to "EMWfemale18neutral.bmp"
https://docs.google.com/spreadsheets/d/1wipJpWNRZpVGJH1KN7NV_oLBDlu2b1OiYjF1pSL2u_A/edit#gid=751157275

@noah10 could you change the stimulus on your end?

**Comment by noah10** [comment]
This is fixed. To test it you may want to use this link (but note that doing so may interfere with your ability to do daily tasks in the correct order, so you may want to use a different account): https://dev.heartbeamstudy.org/daily-tasks/?tasks=face-name&setNum=5 .

**Comment by nashiro** [comment]
I tested it and it looks good. thank you
