### ISSUE TITLE
for verbal learning test, are interim prompt screens necessary?

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#130]
The delayed verbal learning test involves a phase where I'm prompted to enter all modes of transport, furniture, animals etc. There is an initial screen for each of these prompts, the participant has to press the space bar, and then the instructions are repeated with the fill-in box interface. Do the instruction screens before the fill-in screens fill some purpose? If not, we could perhaps eliminate them?

**Comment by mjDahl** [comment]
Hi Mara,
I think the initial instruction screens could be removed for the cued recall. We just tried to make sure that participants do read each instruction

**Comment by maramather** [comment]
Ok, thanks. If you might be willing to file a new issue that specifies which screens could be omitted, that would be great (or if you think it is better to keep them, that is ok - I am just trying to reduce any unnecessary time for participants).

**Comment by mjDahl** [comment]
I have added a new issue for this (see #148 ). #130 can be closed
