### ISSUE TITLE
Phsyical Activity Survey

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#131]
Could you add one line space between "Run more than 10 miles per week or ...." and "Body weight (lbs)"?

Additionally, I noticed that "Please fill in the appropriate values for yourself for the following variables" is missing before "Body weight (lbs)"
https://docs.google.com/document/d/1cyUZZa8EkaDQe7oW29zwImlv_5OQKqAWqmLBjsAl0SI/edit?usp=sharing

![physical activity](https://user-images.githubusercontent.com/26439818/142079503-0eb10b7a-9399-46bf-9ccd-3ef485e39ac6.png)

**Comment by noah10** [comment]
These are both fixed. You may need to shift + reload to get the latest version.

**Comment by nashiro** [comment]
Looks good. Thank you.
