### ISSUE TITLE
Reading the Mind in the Eyes Test- photo did not show in practice trial on day1

### ISSUE THREAD

**Issue by HyunjooY** [EmotionCognitionLab/pvs#137]
In the first day, photo did not show in practice trial. I could see only 4 options.

**Comment by noah10** [comment]
It looks like we don't have image preloading turned on for this task. We should turn it on and see if it fixes the problem.

**Comment by noah10** [comment]
This is ready to be tested. You may need to shift + reload to get the latest version.

**Comment by HyunjooY** [comment]
I will. Thank you!

**Comment by HyunjooY** [comment]
I tested it with an individual task link with another account (davidmom213@gmail.com).
The practice trial image was shown successfully. Do you want to test it in daily tasks mode? Then can you remove my data or something and allow this account to start daily tasks? Sorry..I forgot I should not use the same account for the individual task and daily tasks.

**Comment by noah10** [comment]
No, I don't think that we need to test it in daily tasks mode - the code change was in the task itself, which means that it will be the same no matter whether it's done individually or as part of the daily tasks. Thanks for testing; I'll close this now.
