### ISSUE TITLE
sign in problem

### ISSUE THREAD

**Issue by HyunjooY** [EmotionCognitionLab/pvs#138]
I had an issue when I try to sign in on laptop. So I had to reset a password. 
And now it does not allow to access the daily task page (message below).
I am not sure this is something I should fix on my laptop or my account to be fixed. 
My account: hyunjooy@usc.edu
_________________________
This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by noah10** [comment]
This was my mistake, and is fixed now.
