### ISSUE TITLE
Could we skip the practice trials for the pattern separation task in sessions after the first one?

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#139]
I think we could skip the practice trials for the pattern separation task after the first time they do the task. Interested in what Kaoru thinks (Kaoru, perhaps you could ask the group in the team meeting tomorrow).

**Comment by maramather** [comment]
@nashiro, wanted to make sure you saw this.

**Comment by nashiro** [comment]
The team agreed with you, Mara.
I've removed the practice trials for the pattern separation task after the first time they do the task (i.e., Set 2 & 5, Set 3 & 6).
@noah10 - could you remove the practice trials from these sets and update the instructions?

https://docs.google.com/document/d/1Fpgh3ecc2w6521SwkuyPWWRcfPbwtNmZdjiljqe5y_A/edit

**Comment by noah10** [comment]
This is changed and ready for testing. Remember that you may need to shift + reload to get the latest version.

**Comment by nashiro** [comment]
Is there a way to test Set2 and/or Set3 individually?

**Comment by noah10** [comment]
You can add &setNum=2 or &setNum=3:

https:://dev.heartbeamstudy.org/dailyTasks/?tasks=pattern-separation-learning&setNum=2

**Comment by nashiro** [comment]
The link didn't work unfortunately (I tried 3 different browsers but none worked).

**Comment by noah10** [comment]
It had a typo in it. I've fixed it now.

**Comment by nashiro** [comment]
It looks good.
Could you add 'twice' to the following sentence which appears in the second instruction page?
You will see 30 items. --> You will see 30 items twice.

**Comment by noah10** [comment]
OK - I've added "twice".

**Comment by nashiro** [comment]
I see it. Thank you.
