### ISSUE TITLE
verbal-fluency doesn't account for typing skill

### ISSUE THREAD

**Issue by Floozutter** [EmotionCognitionLab/pvs#14]
Mara and others mentioned during the PVS team meeting today that adapting the task into digital form where typing is required may introduce a working-memory component into it. A couple of solutions were suggested:
- Add a final yes-or-no question to the end of the task asking if the participant managed to finish typing every word they thought of (or something along those lines).
- Add a final scaled (1 to 5?) question to the end of the task asking about the participant's typing skill.
- Add an actual typing test.

For the actual typing test suggestion, I think a couple of the PVS team members (Alex and Martin?) are looking into typing tests online, so we might not have to actually add any substantial code. Hopefully.

**Comment by noah10** [comment]
In the Slack channel Alex and I discussed that the conditions of the typing test might vary so much from the conditions of verbal-fluency that we could get substantially different results and that it might be best just to measure the participant's letters-per-second typing speed while s/he is doing the task.
