### ISSUE TITLE
pattern separation practice recall trials only display target stimuli, not lure or new

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#140]
It seems to me that it would be good to have at least one item that does not fit into a shoebox and at least one item that is not old on the test.

**Comment by maramather** [comment]
@nashiro, wanted to make sure you saw this.

**Comment by nashiro** [comment]
Agreed (but I think you meant we should have at least one item that fits into a shoebox?)
I changed the stimuli. Noah, could you update the stimuli on your end (see the link below)? 

I realized that the reason why we only see old stimuli during the test is that it currently shows only the first 4 items in the list. Could you show all 8 items during the practice test?
https://docs.google.com/spreadsheets/d/1In7052RufUty29ta4QsR0YwnlyZCMAvsXk38ng8FCbU/edit#gid=769377024

**Comment by noah10** [comment]
@nashiro The spec says to "Present 4 objects (“Target”)". It sounds like you want to change that so that we ignore whether the image is "target", "lure" or "new" and just present all of them. You want to do this *only* for the practice stimuli and *not* for the regular stimuli, is that correct? (That is, for the regular stimuli we'll continue to show only the "target" images during the encoding phase.) If so, I'll update the spec to reflect that.

**Comment by nashiro** [comment]
Sorry about the confusion. But no, we want to present 4 objects during the practice **encoding** trials and 8 objects during the practice **test**.

There are two parts to the practice trials.
1) Practice Encoding: We want to "Present 4 objects (“Target”)" as you said.
2) Practice Recognition Test: We want to "Present 8 objects (“Target” “Lure” and “New”). Please see two paragraphs below the "Present 4 objects (“Target”)" paragraph you are referring to. 

https://docs.google.com/document/d/1Fpgh3ecc2w6521SwkuyPWWRcfPbwtNmZdjiljqe5y_A/edit

**Comment by noah10** [comment]
This is fixed and ready for testing. Remember that you may need to shift + reload to get the latest version.

**Comment by nashiro** [comment]
I tested it and saw 8 objects during the practice recognition test - thank you.
However, one object (i.e., nob_pamphlet1.jpg) did not appear during the practice encoding AND during the practice recognition test. It was black/blank.

**Comment by noah10** [comment]
That's odd - something must have gone wrong when I did the PNG->JPG conversion. I've uploaded a new version; it should be available in a few minutes.

**Comment by nashiro** [comment]
I tested it just now and saw the object. Thank you and please close this issue.
