### ISSUE TITLE
updates on pattern separation instructions

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#143]
Could you please update the instructions for the pattern separation task Set 1 & 4 (see the yellow highlights in the specs)? Please let me know if they don't make sense. 
https://docs.google.com/document/d/1Fpgh3ecc2w6521SwkuyPWWRcfPbwtNmZdjiljqe5y_A/edit

**Comment by noah10** [comment]
This is changed and ready for testing. Remember that you may need to shift + reload to get the latest version.

**Comment by nashiro** [comment]
I tested it and it looks good. thank you
