### ISSUE TITLE
show each object for 3 seconds during the practice encoding trials for pattern separation

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#144]
Could you show each object for 3 seconds during the practice encoding trials for pattern separation (instead of 2.5 seconds)?
https://docs.google.com/document/d/1Fpgh3ecc2w6521SwkuyPWWRcfPbwtNmZdjiljqe5y_A/edit

**Comment by noah10** [comment]
This is changed and ready for testing. Remember that you may need to shift + reload to get the latest version.

**Comment by nashiro** [comment]
I tested and it looks good. Thank you.
