### ISSUE TITLE
 for verbal learning test, please include confirmation before ending input after pressing stop

### ISSUE THREAD

**Issue by mjDahl** [EmotionCognitionLab/pvs#149]
In the verbal learning test, participants enter words and enter each entry by pressing _enter_. They stop this recall phase by pressing _stop_. Sometimes it happens that participants inadvertently press _stop_ instead of _enter_ to confirm a word. To avoid a premature ending of the recall phase, it would be good to have participants confirm they have recalled all words they could remember after pressing _stop_

**Comment by noah10** [comment]
This is ready to be tested. If it works as requested please close this issue.

**Comment by mjDahl** [comment]
This works great, many thanks!
