### ISSUE TITLE
Mind in Eyes task: Day1 looks not fully randomized

### ISSUE THREAD

**Issue by HyunjooY** [EmotionCognitionLab/pvs#155]
I am analyzing the eyes task data and I found day1 has fixed 6 items and only order is randomized; item No: 12, 18, 25, 31, 35, 36.
I remember we changes to randomize fully for all 6 days and only day1 looks not fully randomized. 
I attach the screenshot of frequency table. Can we fix it?
![image](https://user-images.githubusercontent.com/41126740/145471682-a505e5db-a575-46c8-a9b4-e288e337df40.png)

**Comment by noah10** [comment]
I think that something has been missed here. The original stimuli were organized by set. When a participant does the task we look at which set s/he is doing and show him or her the stimuli for that set, in a random order. Is that not what "6 days:randomized, with different trial sets for each day" in the spec means? We have a different trial set for each day and we randomize the order of the words in that trial.

**Comment by HyunjooY** [comment]
I think that was original plan, but when we had a meeting (Mara, Noah, and me), Mara suggested we could randomize fully, so not fixed 6 days set. 
Sorry. I think I updated it only in word list document in google spread sheet https://docs.google.com/spreadsheets/d/1cq3mgMhn43naoNOVlQIjM_c2EYUQjKtNWkKyFx9UUXQ/edit?usp=sharing
And in the response table, day2~day6 looks not having fixed 6 stimuli.  
I put Day1~Day6 based on the date for each person. I guess stimuli were fixed but day information are messed up.
I thought the stimuli were randomized for day2~ day6. 

For me, it is totally fine if we use fixed 6 day set and only the presentation order is randomized like current setting.
I will ask Mara if it is fine.

**Comment by maramather** [comment]
I'm fine with having different trial sets for each day or randomizing fully. Whatever will be easier at this point.

**Comment by noah10** [comment]
Leaving it the way it is is obviously easiest. :-) Hyun Joo, if we stick with what we have can this issue be closed or is there still a problem to be resolved?

**Comment by HyunjooY** [comment]
Thank you! 
You can close this issue.
