### ISSUE TITLE
N-back: increase targets per trial and decrease number of total trials 

### ISSUE THREAD

**Issue by ycazaherrera** [EmotionCognitionLab/pvs#156]
The n-back is bit a long. To shorten it, we will: 

Increase the number of target items from 4 to 5 per trial; 
Drop one trial per load - participants will now complete 9 trials (3 rounds of 0-, 1-, and 2-back) instead of the current 12 trials (4 rounds of 0-, 1-, and 2-back).

This information has already been updated in the n-back task specs document.

**Comment by noah10** [comment]
This change is deployed and ready to test.

**Comment by ycazaherrera** [comment]
Looks good.
