### ISSUE TITLE
Turn off auto-correct/spelling assist feature in text input forms

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#161]
If possible we should turn off any feature that marks misspelled words wherever users are entering words (e.g. verbal learning).

**Comment by noah10** [comment]
This fix has been deployed and is ready to be tested.

**Comment by choipaul92** [comment]
I just tested set 4 and the auto-correct/spelling assist is indeed turned off during the verbal fluency tasks (verbal learning task is in set 5 so i'll confirm that too). 

I will say though I use a macbook with a touchbar and when I type in letters, it does give me words as suggestions. I found myself using the words that the touchbar recommended me.

**Comment by choipaul92** [comment]
Just tested out Verbal Learning and the auto-correct/spelling assist feature is turned off in the browser; however, it is still on via my MacBook touchbar

**Comment by noah10** [comment]
Unfortunately there's nothing to be done about the MacBook touchbar; we have no way to control that. Good to know, though! Sounds like we can resolve this.
