### ISSUE TITLE
please add text at the beginning of daily task to let participants know which set they are on

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#163]
Text for Set 1:
Welcome! You will be asked to do 6 sets of daily emotion and cognition tasks over 6 different days. You are about to start Set 1.

Text for Set 2-6:
Welcome back! You have completed X sets out of 6 of daily tasks. You are on Set X.

**Comment by nashiro** [comment]
Thanks Noah. Paul agreed to test it (thanks Paul!).

**Comment by choipaul92** [comment]
Just completed set 1 and I saw the prompt about which set I am doing. I'll test this for the next few days to confirm all the prompts for ea/ set

**Comment by choipaul92** [comment]
all sets had the prompts about which set they are on
