### ISSUE TITLE
jspsych-percent-sum.js fields are too permissive

### ISSUE THREAD

**Issue by Floozutter** [EmotionCognitionLab/pvs#18]
Examples:
- `"1.1" -> 1`
- `"1e1" -> 1`
- `"-1" -> -1`

Basically, don't just `parseInt(inp.value, 10)`.
You should probably export a function `(_: string) => number` for testing in `jspsych-percent-sum.test.js`, too.
Valid arguments return ~~integers~~ ~~naturals~~ non-negative integers, invalid arguments return `NaN`?

**Comment by noah10** [comment]
Fixed in PR #20
