### ISSUE TITLE
make it easier to separate pre- and post-intervention experiment data

### ISSUE THREAD

**Issue by Floozutter** [EmotionCognitionLab/pvs#185]
In the experiment data emitted from `admin/download`, it currently isn't obvious how to partition the trials by Daily Tasks T1 / Daily Tasks T2. Potential workaround: find and mark the ~5 week gap in the data per user before analysis.

**Comment by noah10** [comment]
If the setNum for the "taskStarted" result (which should be the first result written at the start of each experiment) is <= 6 it is from the pre-intervention baseline (T1). Otherwise it is from the post-intervention baseline (T2).
