### ISSUE TITLE
add "dropped" feature to admin tool

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#192]
We've decided to drop anyone who misses a day of the cognitive baseline tasks (at least if they don't catch up after Paul nudges them). We'll need some way in the admin tool to mark someone as dropped and to add that information to the database so that we don't keep nagging them to do their daily tasks (and so that we can filter out their partial data, etc.).

**Comment by Floozutter** [comment]
Added in #214 without sorting.

**Comment by noah10** [comment]
Merged and deployed. Closing.
