### ISSUE TITLE
Creating a new field in Pattern Separation Task JSON files [Learning + Recall]

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#196]
Rules for the "correct" column:

- Yes, it would only appear when isReall=true (i.e., we don’t care about whether they are correct about it fitting in a shoebox or the other question).

- When participants saw “Target” and their answer was “1 = definitely old” OR “2 = maybe old,” they are correct.

- When participants saw “Lure” and their answer was “3 = maybe new” OR “4 = definitely new,” they are correct.

- When participants saw “New” and their answer was “3 = maybe new” OR “4 = definitely new,” they are correct.

- Otherwise, they are incorrect.

**Comment by maramather** [comment]
Noah says that you have access to the JSON file and the code that transforms it to a CSV file. Someone else on the team should be able to modify the code to transform the JSON in the desired way to a CSV. @nashiro or @HyunjooY - is there an RA that you think could figure this out after discussing it with @choipaul92?

**Comment by HyunjooY** [comment]
Dana could modify it. But she will return to work in a few weeks from maternity leave.
So, I will look into it. 
@choipaul92, would you share the existing code to convert JSON to CSV for the pattern separation task?
You can send it via slack.

**Comment by noah10** [comment]
This is now incorporated into the code that puts all of the cognitive assessment data into Flywheel.
