### ISSUE TITLE
Spatial orientation task: go down to 4 trials during 1m 40 s per a day

### ISSUE THREAD

**Issue by HyunjooY** [EmotionCognitionLab/pvs#197]
Hi Noah and David,
We decided to shorten the task based on the feedback from the pilot participant.
So we have 12 items for 5 min per day and change to 4 items for 1 min 40 seconds per day.
I modified the specification and updated the stimuli list for the shortened version. 
https://docs.google.com/document/d/1azzNVrrh6fffMxtH5cdOX7cBihSCPoXqVnZsbkDST3c/edit?usp=sharing
You can find a tab "list_trial_4item_version"

Could you change the task based on this specification and list? 
Also, please change the instruction page before the main trial like below.
"There are four items on this test. You will have 1 minute and 40 seconds to complete these items."
Thank you!

**Comment by Floozutter** [comment]
Fixed in #200.
