### ISSUE TITLE
Include set number in data output for cognitive tasks

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#198]
Is possible to create a column in the data where we know which set they are on?

**Comment by noah10** [comment]
I was just talking with David about this. These data are in the JSON file, but they're a little trickier than usual to get into the CSV file. He's going to modify his JSON->CSV script so that it adds a column with set number for all of the tasks.

**Comment by noah10** [comment]
Merged in the [label_setnums.py](https://github.com/EmotionCognitionLab/pvs/blob/main/baseline/client/scripts/datatools/label_setnums.py) code, which addresses this.

**Comment by noah10** [comment]
Kaoru reports that the code is working. Closing.
