### ISSUE TITLE
Report learning/recall interval in Pattern Separation Task 

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#207]
Can we create a field in the Pattern Separation Task that calculates the time between learning and recall (time between the end of learning and start of recall)?

**Comment by noah10** [comment]
Per @maramather , we will consider the start of pattern-separation-recall to be when the user presses the space bar on the first instruction screen.

**Comment by noah10** [comment]
Paul says this looks good.
