### ISSUE TITLE
Change the missed trial feedback for the flanker task 

### ISSUE THREAD

**Issue by arielle68** [EmotionCognitionLab/pvs#209]
Currently, if participants don't respond within the time frame set for each trial, the arrows disappear and the message "answer faster next time" appears. In the future, instead of showing this message, the screen should turn red.
Instructions for screens 5 and 9 on day 1 and screen 1 on day 2 will reflect this change 

SCREEN 5:
Now, let’s try the task. Keep your eye on the cross. Answer as fast as you can without making mistakes.  You will receive feedback after each try. If you don’t respond within the timeframe, the screen will turn red to remind you to answer faster next time. Whenever you are ready, press the spacebar to continue. 

SCREEN 9:
Now you are ready to do the task without feedback. Keep your eye on the cross and answer as fast as you can without making mistakes. Remember if you don’t respond within the timeframe, the screen will turn red to remind you to answer faster next time. Whenever you are ready, press the spacebar. 

SCREEN 1:
We are going to ask you to do the arrow task again. Remember in this task you will see a row of arrows. You should choose the key that matches the way the MIDDLE arrow is pointing. If the middle arrow is pointing right, press the right arrow key. If the middle arrow is pointing left, press the left arrow key.

**Comment by noah10** [comment]
This is ready to be tested.

**Comment by choipaul92** [comment]
Instructions are changed on all sets (pre+post) and the red screen appears when you miss entering a key. I will say that the shade of red was really bright in contrast to the yellow background (which is good because it does get your attention).

Do you guys think we should add the instructions about red screen = missed entry on sets 3,5,9 and 11? That info is only shown on set 1 and 7

**Comment by maramather** [comment]
Thanks Paul!

If you don't think the instruction addition is essential (i.e., after a few red flashes, the participant would figure out that it is negative feedback), then let's leave it as is.

**Comment by choipaul92** [comment]
Sounds good!
