### ISSUE TITLE
Add sleep questionnaire to set 4 during pre-intervention phase and set 10 in post-intervention phase

### ISSUE THREAD

**Issue by arielle68** [EmotionCognitionLab/pvs#211]
The new sleep quality measure (Pittsburgh sleep quality survey) will be administered as a part of set 4 during pre-intervention phase

**Comment by arielle68** [comment]
Here is the spec:
https://docs.google.com/document/d/1VAiBQXMDOKcbWGlp08LWGJT3g5C-dMFWDEWiBN97f4c/edit

**Comment by maramather** [comment]
Hi Padideh, 
I wasn't able to view the spec, but would like to check whether it reflects the change where we replace the Pittsburgh sleep quality index with Eppworth sleepiness scale and Karolinska sleepiness. 

The spec linked here (see highlighted line) still involves the Pittsburgh sleep quality index: https://docs.google.com/spreadsheets/d/1hYrIFnyd5hMNr_vbmOjVXs6xhPQV7s32ixpF-W-D9Tk/edit#gid=713375495

Would you update the linked spec on that spreadsheet so it refers to the Eppworth sleepiness scale and Karolinska sleepiness?  Thanks so much!

**Comment by arielle68** [comment]
The spec for the sleep questionnaires is updated. Please let me know if any information is missing/not clear. Thanks!

**Comment by noah10** [comment]
@arielle68 Is this supposed to be added only to the pre-intervention phase, or also to the post?

**Comment by maramather** [comment]
It should be added to both.

**Comment by noah10** [comment]
This can now be tested, @arielle68 .

**Comment by maramather** [comment]
Paul, if you could add this to your list of things to test that would be great.

**Comment by choipaul92** [comment]
Will do!

**Comment by choipaul92** [comment]
Set 4+10
Everything is updated but the last question on the sleep survey has an 8-point Likert scale but the specs indicate a 9-point Likert scale (it's missing "alert" option).

**Comment by noah10** [comment]
Thanks for catching that. I've fixed it now.

**Comment by choipaul92** [comment]
Just tested again! Everything is updated
