### ISSUE TITLE
dashboard checkboxes don't work correctly with `MockClient` in browser

### ISSUE THREAD

**Issue by Floozutter** [EmotionCognitionLab/pvs#212]
Checking and unchecking do not work in browsers if the dashboard is initialized with `MockClient`. This may be because the browser's handling of `event.preventDefault();` writes over the `this,setMarkable();` and `this,clearMarkable();` calls. It is possible that this issue only happens with the mock client because the `await`ed promises resolve immediately instead of with some delay. (The delay would allow the `event.preventDefault();` handling to occur before the `this.setMarkable();` or `this.clearMarkable();`.)

Tested on Firefox and Chrome.

**Comment by Floozutter** [comment]
Fixed in #213, hopefully.

**Comment by noah10** [comment]
This has been merged and deployed. Feel free to close it if it's working for you.
