### ISSUE TITLE
URL changes after logging in

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#218]
I tried to log in to the HeartBEAM app today to access the physical activity survey at this link provided: https://dev.heartbeamstudy.org/daily-tasks/?tasks=physical-activity.  I was directed to log in, but after logging in, it took me to start the cognitive tasks instead.  I noticed that the URL had changed after logging in to: https://dev.heartbeamstudy.org/daily-tasks.  I had to re-paste the physical activity survey link to complete it.  I'm not sure if participants will ever be directed to a particular page through a specific app URL, but if they are and something similar were to happen, they might not realize that the URL changed after logging in.  Is there a way that, even after logging in, they are taken to the original URL they were trying to access?

**Comment by choipaul92** [comment]
I also had difficulty accessing the Physical Activity. For me, I was able to access it by continuing to start the cognitive sets (I randomly tried this & it worked).

**Comment by noah10** [comment]
We should never send regular users to a particular part of the cognitive baseline - the entire thing can become a mess if we do that, as it becomes tricky to figure out how many days they've done, whether the required amount of time has elapsed between various parts that have timing requirements, etc.
