### ISSUE TITLE
Random Paced Breathing: Adding Instructions

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#219]
There should be instructions on how to do Random Paced Breathing when the lines move horizontally.

**Comment by nashiro** [comment]
I just noticed that there are instructions on the horizontal lines already (see p. 16 in https://docs.google.com/document/d/114YL_HoACHEJUgOy0q_SrYUeAb6_g432atZELOGsvSA/edit#)
It says, "When the ball is not going up or down, you should pause your breathing."

Perhaps, these instructions were skipped in the pilot version of the app (but not the full version of the app)?

**Comment by noah10** [comment]
Correct - I just need to add them to the app.

**Comment by choipaul92** [comment]
"Pause your breathing when the ball is not going up or down" has been added
