### ISSUE TITLE
Random Paced Breathing: emWave Sessions Not being recorded

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#221]
Not all sessions were being recorded on emWave (including ones that were longer than 5 minutes)

**Comment by noah10** [comment]
Can you give me the dates and times for the sessions that weren't recorded for you? With that information I can take a look at your heartbeam data for those dates/times and see if it gives any clues as to what happened.

**Comment by choipaul92** [comment]
For me, I believe it was 7/21, 7/25, 7/26, 7/28, 8/1, 8/3

**Comment by noah10** [comment]
It looks like this might have been due to closing emWave (and/or removing the EmWaveListener from the DOM) before it had a chance to save the session information. Commits 7933df9c5697d456e2 and 2967608cf04660c534947 address those problems.

**Comment by noah10** [comment]
Two testers report that emWave sessions are now being saved consistently. Closing.
