### ISSUE TITLE
Random Paced Breathing was not given on Day 7 & 8

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#223]
Hi Noah,
I  completed the 8-day pilot study. On Day 7 & 8, the App showed a blank screen after I completed the Lumosity segment and clicked "here." So I was unable to do the random paced breathing segment on Day 7 & 8. I'm not sure if this is an issue that needs to be fixed or not since other people didn't seem to have had this problem. But I just wanted to report it to you. Below are my notes:

Day 0 (7/11): I completed the physical activity survey.

Day 1 (7/12): I installed Noah's App on a lab laptop. The app guided me to do 5-min resting state followed by 4-s paced breathing.
Re-opend the app, which guided me to play Lumosity games. After the Lumosity segment, the app told me to come back tomorrow.

Day 2 (7/13): The app guided me to play Lumosity games followed by 5-min resting state.

Day 3 (7/14): The app guided me to play Lumosity games followed 2 sets of random paced breathing.

Day 4 (7/15): The app guided me to play Lumosity games followed 2 sets of random paced breathing.

Day 5 (7/16): The app guided me to play Lumosity games followed 2 sets of random paced breathing.

[Note: I skipped 7/17]

Day 6 (7/18): The app guided me to play Lumosity games followed 2 sets of random paced breathing.

Day 7 (7/19): The app guided me to play Lumosity games and ENDED without the random paced breathing segment (i.e., After I completed the Lumosity segment and clicked "here" [see Image #1 below], the App showed a blank screen [see Image #2]).

Day 8 (7/20): Same as Day 7

![HeartBeam_End_of_Lumosity](https://user-images.githubusercontent.com/26439818/185512902-b5970bcd-39ee-4ec7-a8d0-c7dd771a2f82.PNG)
![HeartBeam_After_Clicking_Here](https://user-images.githubusercontent.com/26439818/185512916-9241b51e-412e-4f67-95e9-b2147e734765.PNG)

**Comment by noah10** [comment]
Unfortunately I didn't find anything in the logs that would help us figure out what went wrong here, which is surprising. It looks like some sort of application error happened, but without logs I'm unlikely to figure out what it was. I'll leave this open so that we can add more information if it happens again, though.

**Comment by nashiro** [comment]
Sounds good. Thanks!

**Comment by noah10** [comment]
I did just find a bug related to this: If for some reason we don't generate any breathing regimes you'll end up with a blank screen. I don't know if that's what happened here (or, if so, why we didn't generate any regimes), though - it's just something with the same symptom.

**Comment by noah10** [comment]
Closing this since we haven't seen it again.
