### ISSUE TITLE
Lumosity message

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#225]
The message at the top ("After completing the Lumosity segment, please click here") may be confusing because participants may not know that they are seeing Lumosity below.  It resembles a pop up ad that I usually quickly close to maximize view of the screen.  I'm not sure if we should change the color or add an icon to distinguish it.  Or maybe change the text to something like: "Please begin your Lumosity game session below.  When you complete all of the games, please click here."

**Comment by noah10** [comment]
The Lumosity screen is labelled "lumosity" right beneath the "After completing..." text, so hopefully people will understand what we're talking about. I'm open to changing the design (though a little concerned that we could inadvertently make it look *more* like a pop up ad if we don't user-test the changes) or the text, but in either case it would be important that the change not take up more space, which is already quite limited. Unfortunately the text change you suggest above would take up more space. Maybe just "After completing what's below please click here"?

**Comment by cho890** [comment]
Or "After completing the Lumosity games below, please click here?"  Could we make the banner width a little smaller and maybe add the heartbeam icon at the front?

**Comment by noah10** [comment]
We can't change the banner width because it's not a banner (though I can see how it looks like one), but I did make the text change and add the icon.
