### ISSUE TITLE
Back-to-back sessions

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#226]
It seems like someone can do back-to-back breathing sessions if they wanted.  I hit “Start New Session” right after finishing the first one, and it allowed me to do the next session, but there should be at least a 30 minute gap between them.  Is there anything that can stop people from doing the second session right away?  If not, maybe there should be a message at the top of the screen saying, “Please only complete this next session if it has been at least 30 minutes from the end of your first session."  Or maybe the "Start New Session" shouldn't be displayed right after the end of the first session?

**Comment by noah10** [comment]
There is actually no requirement to wait 30 minutes - this was discussed in Slack earlier.
