### ISSUE TITLE
Emotional Memory Task

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#229]
As requested, I am creating an issue here for the emotional memory task to be programmed.  Below are the links to the specs and stimuli.  Please let me know if you have any questions or need clarification.  Thanks!

1. Specs:  https://docs.google.com/document/d/11GW44ggC3QaAEP-PI-HmrESuxYCU_hxmbysGaWMuSi4/edit
2. Specs Slideshow:  https://docs.google.com/presentation/d/1Wg2-J4acT-HwezoqGPG6nx4WXowUzXdy4TVQ7xfmU0g/edit#slide=id.g1459378d68e_0_26
3. Stimuli:  https://drive.google.com/drive/folders/1vFjrXD26XuYRhaYab3I7-zojonayGH2U?usp=sharing

**Comment by noah10** [comment]
This is in the app and ready to be tested.

**Comment by choipaul92** [comment]
I just finished all 6 sets and noticed some things on the emotional memory task: 

-the pictures were off-centered and to the right

-some of the pictures also had black borders; not all pictures were the same size

-the instructions were a bit confusing: participants might get confused if they can select numbers ranging from 1 through 9 OR only be able to select 1, 5 or 9. I also think the instructions should be (1 = very negative,  5 = neutral, 9 = very positive) instead of "(1 = very negative, 9 = very positive, with 5 = neutral)"?

**Comment by noah10** [comment]
Christine, I'm assigning this to you to decide if you want to change the pictures and the instruction text per Paul's suggestions. If you do want to change the pictures please try to keep the file names the same as the original images and let us know where to download the new ones.

**Comment by cho890** [comment]
@noah10 In my testing, I have not observed Paul's first comment that the pictures were off-center and to the right.  Could you look into what may be causing this?  His second comment that all of the images are not the correct size are correct.  These images are pulled from different databases, and if I try to resize all to be the same size, it may distort the images. 

I do think the instructions need to be revised and there are some warning instructions missing from the welcome screen that were in the specs.  Could the following edits with ** ** be made?

Day 4 edits
1. For this task, you will view a set of pictures presented one at a time. You will be asked to rate **on a scale of 1 to 9** how negative, neutral, or positive you find each picture (1=very negative, 5=neutral, 9=very positive). There are no correct answers; we want to know how these pictures make people feel.

**NOTE: This task involves viewing and labeling emotional pictures, both pleasant and unpleasant. The emotions typically evoked by the pictures include disgust, fear, contentment and amusement.** 

2. On the screen after a picture is presented, could the instructions instead read, "**Please press a number key to rate each picture on a scale of 1 to 9, where 1 is very negative, 5 is neutral, and 9 is very positive)**. If you did not see **the picture**, please press ‘x’”

Day 6 edits
3. Earlier this week, you viewed and rated a series of emotional **pictures**. In the box below, please describe each **picture** you recall in as much detail as possible so that someone will be able **to** identify the **picture** you describe.
4. Please click **the "Continue"** button after **entering** each description.
5. The screen that comes after entering an image, could the buttons be centered?  They seem to be left aligned, which is strange.  Could the button that says "Describe another image" be replaced with "Enter another description for a picture I recall" and "Stop describing" be replaced with "I can’t remember any more pictures"?

**Comment by cho890** [comment]
This task has been shortened to include fewer images (18 images shown at both pre- and post-intervention instead of 36).  The images belonging to each set have been changed as a result.  Please update the image sets for this task:  https://drive.google.com/drive/folders/1rbt-zs0tFWWTPMt--eq4i1kzHPgebfjP?usp=sharing.  App specs have been updated to reflect this change as well: https://docs.google.com/document/d/11GW44ggC3QaAEP-PI-HmrESuxYCU_hxmbysGaWMuSi4/edit?usp=sharing

**Comment by cho890** [comment]
> @noah10 In my testing, I have not observed Paul's first comment that the pictures were off-center and to the right. Could you look into what may be causing this? His second comment that all of the images are not the correct size are correct. These images are pulled from different databases, and if I try to resize all to be the same size, it may distort the images.
> 
> The instructions need to be revised and there are some warning instructions missing from the welcome screen that are in the specs. Could the following edits be made?
> 
> Day 4 and 10 instructions
> 
> 1. "For this task, you will view a set of pictures presented one at a time. You will be asked to rate on a scale of 1 to 9 how negative, neutral, or positive you find each picture (1=very negative, 5=neutral, 9=very positive). There are no correct answers; we want to know how these pictures make people feel.
> 
> NOTE: This task involves viewing and labeling emotional pictures, both pleasant and unpleasant. The emotions typically evoked by the pictures include disgust, fear, contentment and amusement.
> 
> Press the spacebar to begin."
> 
> 2. On the screen after a picture is presented, the instructions should read, "Please rate how positive, neutral, or negative you found the preceding picture (1=very negative, 5=neutral, 9=very positive).
> 
> If they do not respond in 5 s, the app should beep and update the text to read, “Please press a number key to rate each picture on a scale of 1 to 9, where 1 is very negative, 5 is neutral, and 9 is very positive). If you did not see the picture, please press ‘x’”
> 
> Day 6 and 12 instructions 3. Earlier this week, you viewed a set of emotional pictures and rated how negative and positive each one was. Now let’s see how many you can remember! For each picture you remember, please describe it in as much detail as possible so that someone will be able to identify the picture you describe.
> 
> For example, instead of "bird," include descriptions like "yellow bird sitting on a tree branch.”
> 
> Press the Enter key after each image description to save your response. Press Stop when you are done.

@noah10 Instructions for the emotional memory task still need to be updated.  While instructions above are accurate, please refer to the specs.  Could this be labeled high priority as well, as it needs to be completed and testedbefore the start of the study?

**Comment by cho890** [comment]
I tried to incorporate everything in the text box, but I recalled you previously saying that you will refer to app specs, as that should have the most accurate descriptions/instructions.  It looks like Set 6 and 12 instructions were updated (see #309) but still has typos.  The instructions for Set 4 and 10 have not yet been updated.

**Comment by noah10** [comment]
OK - the learning (set 4 and 10) instructions should now match the spec.

**Comment by cho890** [comment]
Minor edit for the set 4 and 10 instructions:  Could you add a line space between the NOTE: ... and "Press the spacebar to begin."?

**Comment by noah10** [comment]
Done.
