### ISSUE TITLE
add forced delays to verbal-learning

### ISSUE THREAD

**Issue by Floozutter** [EmotionCognitionLab/pvs#23]
> Currently there is no forced delay between the immediate recall and the long delay recall. Do you think this could be added to prevent participants from completing the long delay recall before the 20 min delay are over?

**Comment by noah10** [comment]
@mjDahl - This has now been implemented. Could you test it out and close this issue if it's working correctly? You'll find it at https://dev.heartbeamstudy.org/verbal-learning/ .

**Comment by mjDahl** [comment]
works like a charm, many thanks!
