### ISSUE TITLE
Minor changes in pattern separation task instructions

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#230]
Based on pilot participants' feedback, I modified the instructions. Could you update the instructions highlighted in yellow in this sepcs?
https://docs.google.com/document/d/1Fpgh3ecc2w6521SwkuyPWWRcfPbwtNmZdjiljqe5y_A/edit

**Comment by noah10** [comment]
This is ready for testing.

**Comment by nashiro** [comment]
Could you send me the link to the task (ideally the link that works without logging in)? Sorry I think I asked you this before but can't seem to find info ...

**Comment by nashiro** [comment]
1) The 2nd page of the instructions for learning for Sets 4,6,10, and 12 has not been updated (please update to the bold text shown below):

Current/Old:
**2nd page** learning instruction: “We will begin the actual task. You will see 30 items twice. Please answer the question presented underneath the item as well as trying to remember them for a later memory test. Please note that the memory test will be given 30 minutes after this viewing session. Please press the spacebar to continue.” (Note: this is correct for Set 2 & 8 learning but not for the rest of the Sets)

Updated/New:
**2nd page** learning instruction: "**Please answer the question presented underneath the item by pressing “y” for “yes” and “n” for “no” as well as trying to remember them for a later memory test. Please note that the memory test will be given 30 minutes after this viewing session. Please press the spacebar to begin.**"

2) The instructions for the memory test for Sets 4,6,10, and 12 has not been updated (please update to the bold text shown below):

Current/Old:
"Now you will be tested on your memory. During the memory test, you will be shown both new and old objects. For an object to be considered “old”, all the objects’ features must be exactly the same. This includes the objects’ color, size, and orientation. If the object’s features do not exactly match the features of the previously shown object, it is considered “new. Please indicate whether each item is 1 = definitely old, 2 = maybe old, 3 = maybe new, or 4 = definitely new. “Definitely old” means you are confident that the object is old. “Maybe old” means that you think the object is old, but not completely sure.  ”Maybe new” means that you think the object is new, but not completely sure. “Definitely new” means you are confident that the object is new. (Please press the spacebar to continue).” (Note: this is correct for Set 2 & 8 but not for the rest of the Sets)

Updated/New:
“**You will be tested on your memory for the objects you saw earlier today. Please indicate whether each item is 1 = definitely old, 2 = maybe old, 3 = maybe new, or 4 = definitely new. (Please press the spacebar to begin).**”

**Comment by noah10** [comment]
@nashiro Should the "Round X" slides stay on the screen for 3 seconds (or some other amount of time) or should the user press the space bar to continue from the "Round X" slide to the trial?

**Comment by noah10** [comment]
Also, it looks like we could unify the instructions to make things simpler. For example, the introduction for sets 2 and 8 differs in only minor, apparently inconsequential, ways from the introduction for sets 4 and 10. Is there any reason we can't unify these to make the software and the experiment simpler?

**Comment by nashiro** [comment]
The user should press the space bar to continue from the "Round X" slide to the trial - please.

**Comment by nashiro** [comment]
The introduction for sets 2 and 8 differs from that for sets 4 and 10 because there is a practice trial for sets 2 and 8, but not for sets 4 and 10. If it helps, I can modify the instructions so that the first page/slide of the instruction is the same for both sets but the second page/slide is different. Please let me know.

**Comment by noah10** [comment]
Sorry, I wasn't clear. When I said "introduction" I was thinking of the text that appears in the section labeled "Instructions (1 min)":

> “In this task, you will first view pictures of common objects. You will see each object twice. For the first round, you will be asked; “Will the object fit inside a lady’s medium shoe box?” For the second round, you will be asked; “Can you carry the object across the room using only your right hand?” After answering these questions for all objects, you will be given a memory test later. (Please press the spacebar to continue)”

Couldn't that text be used for sets 2, 4, 8 and 10? But more generally, anything you can do to make something that is currently different across sets the same would help simplify things.

**Comment by noah10** [comment]
Also, @nashiro, for sets 2 and 8 should the round numbers go 1, 2, 3, 4 or 1, 2, 1, 2? (That is, are the real rounds numbered the same as the practice rounds or do they carry on from where the practice rounds start?)

**Comment by nashiro** [comment]
For sets 2 and 8, the round numbers should go 1, 2, 1, 2 (i.e., the real rounds numbered are the same as the practice rounds).

**Comment by noah10** [comment]
Having looked at this more carefully I see that the only places where there's a significant difference is in the set 2/8 encoding instructions as compared to the set4/6/10/12 encoding instructions and in the practice vs. actual recall instructions. (The set 2/8 and set4/6/10/12 recall instructions look like they're different by accident, as they just differ by the word "now".)

How about if we use this as the actual (not practice) encoding instructions for set 2/8:

> We will begin the actual task. You will see 30 objects twice. For the first round you will be asked, “Will the object fit inside a lady’s medium shoe box?” For the second round you will be asked, “Can you carry the object across the room using only your right hand?” Please answer the question presented underneath the object by pressing “y” for “yes” and “n” for “no” and try to remember them for a later memory test. Please note that the memory test will be given about 20 minutes after seeing all images. Please press the space bar to begin.

...and this for the encoding instructions for sets 4/6/10/12:

> In this task, you will be asked to view a series of common objects and remember them for a later memory test. You will see 30 objects twice. For the first round you will be asked, “Will the object fit inside a lady’s medium shoe box?” For the second round you will be asked, “Can you carry the object across the room using only your right hand?” Please answer the question presented underneath the object by pressing “y” for “yes” and “n” for “no” and try to remember them for a later memory test. Please note that the memory test will be given about 20 minutes after seeing all images. Please press the space bar to begin.

That way only the first sentence varies and I can have one consistent block that follows that first sentence.

The practice vs. actual recall instructions already only vary by the first sentence, so I can use a similar strategy there.

**Comment by nashiro** [comment]
Your changes look fine with me. I modified the spec accordingly. 
If not done already, please show each image for "3" seconds during both practice and actual encoding tasks.

**Comment by noah10** [comment]
OK - all three changes (duration, "round x" screens and text changes) have now been made and are ready to be tested. (In the future, please open one ticket per change.)

**Comment by nashiro** [comment]
Tested. All looks good - thank you!
