### ISSUE TITLE
check Lumosity completion rates during Stage 2 before advancing to Stage 3

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#241]
We want participants to advance from Stage 2 to Stage 3 when the participant has completed at least 3 gameplays of all 12 Lumosity games used in this study. This usually would occur after six Lumosity sessions (each Lumosity session involves playing 6 games from Games Set A or B, so across two sessions, participants play all 12 games). However, if participants sometimes quit Lumosity early, they may need more sessions to accrue three gameplays for all 12 Lumosity games.

The criteria in the application should be that they have completed at least 3 game plays for each of the 12 games.

**Comment by noah10** [comment]
Commit 85742fa3319c441eed4adb0196e0c4f9d5a97dc1 is also related to this issue.

**Comment by noah10** [comment]
This has been superseded by #264 .
