### ISSUE TITLE
Set up screening survey

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#259]
Prospective participants will be screened through the app following the below steps:

1. First, participants will answer the screening questions and hit 'Submit' when done. After these questions are submitted, participants will next provide personal information (name, email, phone, gender).
2. Participants will receive a message informing them if they are eligible or ineligible.
3. Our server will only receive their personal information and a label of "eligible" or "ineligible."
4. Our server will also separately receive screening responses (without personal info), and we will retain a count of each response to each question.

Below are the screening questions and personal information questions.  
[Screening Questions for App.docx](https://github.com/EmotionCognitionLab/pvs/files/10271375/Screening.Questions.for.App.docx)

Below are the messages/statements that participants should see before beginning the survey as well as when they pass or fail the screening.  

**Welcome message and screening statement:**
Thank you for your interest in the USC HeartBEAM study! 

The purpose of this screening is to determine if you are eligible to participate in the study. Please note that the responses you provide will not be tied to your personal information in any way. Screening data will be used to determine eligibility then destroyed. For eligible participants, the study team will retain contact information (i.e. email and phone); for ineligible participants, the reason for ineligibility (i.e. did not meet inclusion criteria, declined to participate, etc.) will be retained. If you have any questions about this study, please contact Mara Mather at mara.mather@usc.edu. If you have any questions about your rights as a research participant, please contact the University of Southern California Institutional Review Board at (323) 442-0114 or email irb@usc.edu.

This screening should take about 10 minutes to complete. If you have any questions, please contact us at uscheartbeam@gmail.com.  Click 'Next' to begin the screening.

**Screening pass message**
Thank you for taking the time to complete this screening survey.  Based on your responses, you are eligible to participate in the study.  Our team will contact you soon regarding next steps.

**Screening fail message**
Thank you for taking the time to complete this screening survey.  Unfortunately, you are not eligible to participate in this study.  If you are currently not a USC Healthy Minds volunteer and would like to learn about other opportunities to participate in USC studies, please visit:  healthyminds.usc.edu.

**Comment by cho890** [comment]
With the recent inclusion of MRI in the study, I have added an updated screening survey document that includes questions verifying MRI eligibility.

**Comment by cho890** [comment]
There was another minor modification to the eligibility criteria and the updated screening questions document has been uploaded.

**Comment by noah10** [comment]
Is there a reason not to just get all of the info on one screen? It's easier for me and seems easier for the participant as well.

**Comment by noah10** [comment]
Also, this bit is slightly confusing: "for ineligible participants, the reason for ineligibility (i.e. did not meet inclusion criteria, declined to participate, etc.) will be retained." 

1. How do we summarize the reason for ineligibility ? For example, if they answer "No" to questions 6 and 10 and "Yes" to question 11 is the reason for their ineligibility "did not meet inclusion criteria", "declined to participate" or "etc."?

2. If we're going to record a reason for ineligibility for each ineligible participant we will also need to record some sort of identifier for the participant. Should that just be some random number, or should we keep their name or contact info?

**Comment by cho890** [comment]
I don't see any reason why it can't be on one screen other than how long they will be scrolling down the page with the inclusion of the MRI questions.

If they fail any of the questions, the reason would always be "did not meet inclusion criteria."  "Declined to participate" is a designation that would be applied after speaking with them over the phone.  For the purposes of this screening survey, anyone who doesn't pass any of the questions would be "did not meet inclusion criteria."  But I don't think the app would necessarily need to place this label.  For clinical trial reporting purposes, we would only need the number of participants who failed the screening, and we would have the number of participants who pass the screening, since we would get their contact information from the app.

We do not need to keep any personal information for participants who do not pass the screening.  We just need a number of participants who failed the screening.  In fact, no personal information for participants who fail the screening can be stored with their responses to screening questions.  This is what is stated in the approved IRB protocol:  _Screening responses will be used to determine eligibility but will not be stored for each participant. We will store aggregate data indicating the number of times each possible answer was provided. Screening responses will never be tied to an individual. For all participants, the study team will retain contact information (i.e. email and phone). Additionally, for ineligible participants, the reason for ineligibility (i.e. did not meet inclusion criteria, declined to participate, etc.) will be retained._

**Comment by noah10** [comment]
OK. It sounds like we can remove "for ineligible participants, the reason for ineligibility (i.e. did not meet inclusion criteria, declined to participate, etc.) will be retained" from the preamble then, since we're not actually storing a reason for ineligibility but instead a count of the number of ineligible.

Mara says that she wants to store (a) the number of times each answer (including gender) is provided by the eligible, and (b) the number of times each answer (including gender) is provided by the eligible. I don't know if that requires any changes to the preamble or IRB, but I certainly wouldn't have thought that we were going to store (a) based on the preamble above. (Though maybe that's more detail than we need to provide in the preamble.) Do you also want to store the name and gender of the eligible in connection with their phone and email?

**Comment by noah10** [comment]
Note to self: Mara says to make question about pregnancy/menstruation required if they answer anything other than "male" to the gender question, so we will need to collect gender info before asking that question.

**Comment by cho890** [comment]
> OK. It sounds like we can remove "for ineligible participants, the reason for ineligibility (i.e. did not meet inclusion criteria, declined to participate, etc.) will be retained" from the preamble then, since we're not actually storing a reason for ineligibility but instead a count of the number of ineligible.
> 
> Mara says that she wants to store (a) the number of times each answer (including gender) is provided by the eligible, and (b) the number of times each answer (including gender) is provided by the eligible. I don't know if that requires any changes to the preamble or IRB, but I certainly wouldn't have thought that we were going to store (a) based on the preamble above. (Though maybe that's more detail than we need to provide in the preamble.) Do you also want to store the name and gender of the eligible in connection with their phone and email?

We need to include "for ineligible participants, the reason for ineligibility (i.e. did not meet inclusion criteria, declined to participate, etc.) will be retained" since that was the language the IRB requested us to display.  You shouldn't need to store anything related to this description.  For clinical trials reporting, we need to report the number of people who:
1. "did not meet inclusion criteria" - we need the number of people who failed the screening survey from the app and Trialfacts
2. "declined to participate" - we determine this from the phone call
3. " other reason" - we determine this from the phone call.  we don't need to specify the reason.

**Comment by noah10** [comment]
Per @cho890, we do want to store the name and gender of eligible participants and we want to leave the preamble as is (that is, don't mention that we'll be storing their name and gender).

**Comment by noah10** [comment]
Mara now says that we don't need to save the number of times each answer (including gender) is provided by the (in)eligible - we're back to just saving the count of ineligible people screened.

**Comment by cho890** [comment]
@maramather I don't see a problem with this.  But we will need to amend what is currently stated in the IRB protocol (second sentence):

"Screening responses will be used to determine eligibility but will not be stored for each participant. We will store aggregate data indicating the number of times each possible answer was provided. Screening responses will never be tied to an individual. For all participants, the study team will retain contact information (i.e. email and phone). Additionally, for ineligible participants, the reason for ineligibility (i.e. did not meet inclusion criteria, declined to participate, etc.) will be retained."

Should we edit the second sentence to say:  "We will store the aggregate data indicating the number of times someone passes or fails the screening."

**Comment by maramather** [comment]
Christine, yes that would be a good clarifying sentence for the IRB.

Noah convinced me it doesn't make sense to include number of times each answer is provided unless we have all participants complete the full eligibility questionnaire even if they would be excluded by an early response. And to reduce unnecessary work on the part of ineligible participants, I do not want them to have to complete more questions than are necessary.

**Comment by noah10** [comment]
Slightly more accurate and more concise would be "We will store the number of times the screening is passed or failed."

**Comment by cho890** [comment]
Great.  I'll make a note to include this in the next amendment.

**Comment by cho890** [comment]
Tested screening survey many times and did not have any major issues.  A few minor updates needed, as described in #310 .
