### ISSUE TITLE
emWave fails to hide

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#269]
Paul reports that emWave is never hidden - the icon always remains on the task bar. Paul, could you please add the details of your Windows version here?

**Comment by choipaul92** [comment]
Lenovo | Windows 11 Pro Education | 22H2

**Comment by noah10** [comment]
Thanks. I'm on Windows 10, so maybe there's something funky going on with Windows 11. Can you please try the following?

1. Make sure neither HeartBEAM nor emWave are running
2. Start emWave
3. Go to TaskManager and click on the "Details" tab (in Win10 you have to click on "More Info" just to get the tab to show up; not sure about Win11)
4. Find emWavePC.exe in the list in the Details tab and make a note of the number in the PID column
5. Open the console window you use to run HeartBEAM and type:
`C:\Users\[your username]\AppData\Local\Programs\heartbeam\hide-emwave.ps1 [PID from step 4]`
(without the [ ] - those are just there to indicate something you have to fill in)

If all goes well, the emWave window should disappear. If all doesn't go well hopefully you'll get an error in your console window that may help me figure out what's going on.

**Comment by choipaul92** [comment]
I tried & it gave me the system cannot find the path specified

**Comment by noah10** [comment]
OK - can you right-click on the HeartBeam icon on the desktop, choose "Properties" and tell me what file the shortcut is pointing at?

**Comment by choipaul92** [comment]
Target : C:\Users\CSF_PB_1033\AppData\Local\Programs\heartbeam\HeartBEAM.exe
Start in: C:\Users\CSF_PB_1033\AppData\Local\Programs\heartbeam

I'm going to download the newest version of heartbeam (the one you posted on slack today). I'll see how that goes

**Comment by noah10** [comment]
OK - when you use the file manager to look at C:\Users\CSF_PB_1033\AppData\Local\Programs\heartbeam do you see a hide-emwave.ps1 file there?

**Comment by choipaul92** [comment]
Yes, I do see a hide-emwave (notepad file)

Okay, so earlier today I tried steps 1-5 again where I enter hide emwave with the PID number. And this time a notepad popped up: 
# Used to hide emwave
param(
    [string]$emwvProcId
)

# Function to maximize/minimize/hide etc. a given window
# Modified version of https://gist.github.com/jakeballard/11240204
# Usage: Set-WindowStyle <Style> <ProcessId>
# Operates on whatever the MainWindowHandle of ProcessId is
function Set-WindowStyle {
param(
    [Parameter()]
    [ValidateSet('FORCEMINIMIZE', 'HIDE', 'MAXIMIZE', 'MINIMIZE', 'RESTORE', 
                 'SHOW', 'SHOWDEFAULT', 'SHOWMAXIMIZED', 'SHOWMINIMIZED', 
                 'SHOWMINNOACTIVE', 'SHOWNA', 'SHOWNOACTIVATE', 'SHOWNORMAL')]
    $Style = 'SHOW',

    [Parameter()]
    $ProcId,
    
    [Parameter()]
    $MainWindowHandle = (Get-Process -id $ProcId).MainWindowHandle
)
    $WindowStates = @{
        'FORCEMINIMIZE'   = 11
        'HIDE'            = 0
        'MAXIMIZE'        = 3
        'MINIMIZE'        = 6
        'RESTORE'         = 9
        'SHOW'            = 5
        'SHOWDEFAULT'     = 10
        'SHOWMAXIMIZED'   = 3
        'SHOWMINIMIZED'   = 2
        'SHOWMINNOACTIVE' = 7
        'SHOWNA'          = 8
        'SHOWNOACTIVATE'  = 4
        'SHOWNORMAL'      = 1
    }
    
    $Win32ShowWindowAsync = Add-Type -memberDefinition @"
    [DllImport("user32.dll")] 
    public static extern bool ShowWindowAsync(IntPtr hWnd, int nCmdShow); 
"@ -name "Win32ShowWindowAsync" -namespace Win32Functions -passThru
    
    $Win32ShowWindowAsync::ShowWindowAsync($MainWindowHandle, $WindowStates[$Style]) | Out-Null
    Write-Verbose ("Set Window Style '{1} on '{0}'" -f $MainWindowHandle, $Style)

}

# hide emWave
Set-WindowStyle HIDE $emwvProcId

**Comment by noah10** [comment]
Can you paste the command you entered at the console?

**Comment by choipaul92** [comment]
C:\Users\CSF_PB_1033>C:\Users\CSF_PB_1033\AppData\Local\Programs\heartbeam\hide-emwave.ps1 6852

**Comment by noah10** [comment]
I think I just realized what the problem is. Instead of using the regular command prompt, can you open a powershell window (Windows menu -> Windows PowerShell -> Windows PowerShell) and paste that command (though obviously with a different process id) there?

**Comment by choipaul92** [comment]
I got this error: 

PS C:\Users\CSF_PB_1033> C:\Users\CSF_PB_1033\AppData\Local\Programs\heartbeam\hide-emwave.ps1 10064
C:\Users\CSF_PB_1033\AppData\Local\Programs\heartbeam\hide-emwave.ps1 : File
C:\Users\CSF_PB_1033\AppData\Local\Programs\heartbeam\hide-emwave.ps1 cannot be loaded because running scripts is
disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ C:\Users\CSF_PB_1033\AppData\Local\Programs\heartbeam\hide-emwave.ps1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\Users\CSF_PB_1033>

**Comment by choipaul92** [comment]
emWave has successfully been hidden since 11/2/22 after applying "Set-ExecutionPolicy Unrestricted"  + "hide-emwave [pip #]" in powershell

**Comment by noah10** [comment]
OK - It looks like we need to be sure to set the execution policy correctly on the participant laptops to get emwave hiding to work. Closing.
