### ISSUE TITLE
Admonish participants who play a given Lumosity game more than 1x/day

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#270]
When processing the Lumosity reports, check for participants playing any game more than 1x/day. If you find that happening, send them an email asking them not to do that.

**Comment by noah10** [comment]
Note: There should be a 'multiPlay' key in the lumos data table that gets set to true when a user plays a game more than 1x in 1 day.

**Comment by noah10** [comment]
@maramather jfyi, so far there are only two users who have ever played a game more than once: One has played two games twice (AvidJar, on 2/2 and 2/3) and one who has played 34 games twice (HepViol, between 2/8 and 2/17).

**Comment by noah10** [comment]
Per Mara, this should go out at 8AM.

**Comment by maramather** [comment]
Text of email:

It looks like you clicked on the "play again" button for one or more of the brain games yesterday. In the future please do NOT click on that button. 

While it is great to see your interest and enthusiasm, for the integrity of our research results, we need all participants to get the same amount of brain game training. So please play all the assigned games every day but no extra ones. Also, please do NOT play any extra brain games outside of the study platform while you are enrolled in the study. Our objective is for all participants to obtain the same amount of brain game practice. We are testing how two breathing practices (one promoting alertness, one promoting relaxation) might affect learning differently. If someone gets a lot of extra practice beyond the assigned set and so progresses faster through the brain game levels, it will look like their breathing practice helped them learn faster, which would not be true.

We're sorry about having that confusing button there, but the brain game interface did not allow us to remove it.

Once again, thanks so much for your dedication to this study. We are excited to see you continue to progress through the brain and breathing training and look forward to seeing you at your next visit to the lab!

HeartBEAM research team

**Comment by noah10** [comment]
This has been deployed to production.
