### ISSUE TITLE
edit first video so that I do not say that participants can view their cognitive baseline scores at the end. 

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#282]
Hi Christine, if this edit would be feasible, that would be great so that we don't have to set up all the infrastructure for telling them their scores. If not, let me know if you think I need to do the whole video over again or if there is some other solution. Thanks so much!

**Comment by cho890** [comment]
I updated the video.  New link is https://youtu.be/eR9zNMfrQ0c

**Comment by noah10** [comment]
Is this the first video in the cognitive baseline or the first video in the home training app?

**Comment by maramather** [comment]
Home training app.

From: noah10 ***@***.***>
Reply-To: EmotionCognitionLab/pvs ***@***.***>
Date: Thursday, December 1, 2022 at 3:42 PM
To: EmotionCognitionLab/pvs ***@***.***>
Cc: Mara Mather ***@***.***>, Author ***@***.***>
Subject: Re: [EmotionCognitionLab/pvs] edit first video so that I do not say that participants can view their cognitive baseline scores at the end. (Issue #282)


Is this the first video in the cognitive baseline or the first video in the home training app?

**Comment by maramather** [comment]
I checked the video and the cut works ok - so this video should now replace the previous one that was at the start of the cognitive baseline.

**Comment by noah10** [comment]
@maramather You say that it's the first video in the home training app but that it should replace the one that was at the start of the cognitive baseline. Which is it - the first video in the home training app or the one at the start of the cognitive baseline?

**Comment by maramather** [comment]
Sorry about that! It is the cognitive baseline one.

**Comment by maramather** [comment]
Christine, when you start testing the study sequence, would you check that the right video is shown at the start (that does not mention the possibility of getting scores from the cognitive baseline/post-intervention?
