### ISSUE TITLE
please fix minor button misalignment 

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#288]
During the emotional memory recall test, the alignment of "describe another image" and "stop describing" buttons should be improved and they should be centered. <img width="503" alt="Screen Shot 2022-12-03 at 5 01 51 PM" src="https://user-images.githubusercontent.com/82665055/205468870-1f38242a-7d6f-4f78-a4c1-ef0a0b33b292.png">

**Comment by cho890** [comment]
I think this issue can be closed as we have removed this from the task and changed how recall is entered.
