### ISSUE TITLE
add instructions/reminders not to write down words during verbal learning task

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#289]
Please add this to the instructions on the screen that appears just before the audio word list plays:

"IMPORTANT: do not write down or type any of the words. See how much you can remember without any assistance!"

**Comment by maramather** [comment]
Kaoru and Christine and I can look for this when we reach the post-intervention phase of the study in some weeks.

**Comment by maramather** [comment]
Paul, would you be able to test this for us? If you need help testing just the verbal learning task, please let Noah know.

**Comment by choipaul92** [comment]
I can test this. Do we know if the post-cog app is ready? If not, I can have my pre-cog data erased and see if it's in the pre-cog.

**Comment by choipaul92** [comment]
Tested both Pre + Post Verbal Learning and new instructions are added
