### ISSUE TITLE
Emotional Memory Task (update image sets, fewer images in overall task)

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#292]
This task has been shortened to include fewer images (18 images shown at both pre- and post-intervention instead of 36). The images belonging to each set have been changed as a result. Please update the image sets for this task: https://drive.google.com/drive/folders/1rbt-zs0tFWWTPMt--eq4i1kzHPgebfjP?usp=sharing. App specs have been updated to reflect this change as well: https://docs.google.com/document/d/11GW44ggC3QaAEP-PI-HmrESuxYCU_hxmbysGaWMuSi4/edit?usp=sharing

**Comment by noah10** [comment]
Please test this carefully. While I think I got all of the images moved to the right place on the server it's always possible I missed one.

**Comment by cho890** [comment]
The sets are accurate.
