### ISSUE TITLE
Automate Post Blood Draw Surveys

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#293]
Blood draw surveys will be sent out to each participant after each mri/blood draw visit. While I'm unsure of the timeline of when we would send it (i.e. 12 hours, 24 hours, 48 hours after the visit @maramather)? 

@noah10 , I don't know if you would want to put this on the app or have it off the app. I will say that I will be checking on qualtrics for each response to ensure that incident reports are made to the IRB on a timely manner.

Qualtrics Link: https://usc.qualtrics.com/jfe/form/SV_ebqB8UDgv1Ges3Y

**Comment by maramather** [comment]
@cho890 - would Ripple allow us to automate emails with links to that questionnaire 48 hours after each blood draw visit?

**Comment by noah10** [comment]
@maramather How long after the visit do we want to send out the survey? Or can it just go out as soon as someone checks off the visit in the dashboard?

**Comment by maramather** [comment]
I think 24 hours would be best.

From: noah10 ***@***.***>
Reply-To: EmotionCognitionLab/pvs ***@***.***>
Date: Thursday, December 8, 2022 at 7:16 PM
To: EmotionCognitionLab/pvs ***@***.***>
Cc: Mara Mather ***@***.***>, Mention ***@***.***>
Subject: Re: [EmotionCognitionLab/pvs] Automate Post Blood Draw Surveys (Issue #293)


@maramather<https://urldefense.com/v3/__https:/github.com/maramather__;!!LIr3w8kk_Xxm!u5v9MOOL6kKqYFybi-dUU_rs7vQ5dGY7AfU8iu4vLfAtIvmWgG34s5cc_8xXGOd1OUZFr9JAhrc3X2m9t8PXcGoEpg$> How long after the visit do we want to send out the survey? Or can it just go out as soon as someone checks off the visit in the dashboard?

**Comment by noah10** [comment]
Per @maramather , visits 2, 3, and 5 will involve blood draws.

**Comment by noah10** [comment]
@maramather Is there any reason that we need to associate the user id with the survey response - to follow up with them, to know that they completed the survey, etc., or should this be totally anonymous?

**Comment by maramather** [comment]
Yes, thanks for checking, we may need to follow up with anyone who had an adverse response so we'll need to associate the ID with the survey. Sorry - I know that is a hassle.

**Comment by noah10** [comment]
@choipaul92 - Can you please set up the qualtrics survey you linked to above to have an embedded data field named "huid"? I'll use that to pass the human (7 character) user id.

**Comment by noah10** [comment]
The qualtrics survey has been updated with the necessary embedded data field.

**Comment by choipaul92** [comment]
Q_URL: https://usc.qualtrics.com/jfe/form/SV_ebqB8UDgv1Ges3Y?huid=AceCrew was recorded

Unique ID: AceCrew

**Comment by noah10** [comment]
@cho890 Could you please provide the subject line and the text we're going to use for this email? (I assume we're just sending it by email, not phone, but if that's wrong then also please provide the text for the SMS.)

**Comment by cho890** [comment]
Subject line: Tell us about your blood draw at your recent lab visit

Hello [participant first name],

We'd like to hear about your experience with the blood draw at your recent lab visit for the HeartBEAM study.  Please click here [insert link] to complete a short survey.

Thank you in advance!

USC HeartBEAM Study Team

**Comment by noah10** [comment]
OK, this is ready to test on dev. Reminders will be sent at noon (PT) for people who had a visit 2, 3 or 5 the previous day. Note that the visit dates in the dashboard are all in UTC, so if you mark off visit3 for someone in the dashboard at 4:30PM PT on 2/10 (for example), the UTC date will be 2/11 and their reminder will go out at noon (PT) on 2/12. Let me know if you want me to manually edit any visit dates in the database to help test.

**Comment by choipaul92** [comment]
Okay, will test this & post with an update!

**Comment by choipaul92** [comment]
Tested this for both visit 2 + 3 & received both emails!

**Comment by noah10** [comment]
Good. Is visit 5 also a blood draw visit?

**Comment by maramather** [comment]
Yes, visit 5 is also a blood draw visit so should also be tested.

**Comment by choipaul92** [comment]
Received Visit 5 blood survey and was successfully recorded on Qualtrics!
