### ISSUE TITLE
minor changes in the breathing instructions

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#296]
Could you remove "We have one remaining task for you today" from the breathing instructions? I think it is a bit misleading to say this since participants have to come back for the second breathing practice.

**Comment by nashiro** [comment]
I need to upgrade emWave to v3.13 before installing a new version of HeartBEAM to double check this change. Paul will send me the instructions on how to upgrade emWave. I'll test a new version of HeartBEAM after that and get back to you.

**Comment by maramather** [comment]
I can confirm it has been removed - I'll close this issue out.
