### ISSUE TITLE
Admin dashboard updates

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#302]
Sequence correction:  Visit 2 on admin dashboard should be after Visit 1.
Missing field:  Projected Start Date, which should come after Subject.  We discussed adding this during our prior meeting to accommodate subjects who might consent but not start the study right away.  This would prevent them from getting reminder emails/texts before they start the study.

**Comment by noah10** [comment]
Can you clarify what you mean by "visit 2... should be after visit 1"? When I look at it I see the column for visit 2 after (that is, to the right of) visit 1. Are you saying that you want to be prevented from checking the visit 2 box if visit 1 has not yet been checked? If so, I would suggest that undo is easy enough (just uncheck visit 2) that this is unnecessary.

Regarding projected start date - I'm going to hold off on that until docusign is done, as that may impact how this gets implemented.

**Comment by noah10** [comment]
Ah, I see - you mean *immediately* after visit 1. So the only change we need to make is to swap the positions of visit 2 and the lumosity+practice breathing status, correct? (Ignoring, again, the projected start date.)

**Comment by cho890** [comment]
Admin dashboard looks good.  Issue is resolved.
