### ISSUE TITLE
Make home training reminders work in PT

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#303]
WedLair did a stage 2 breathing segment at 2022-12-14T05:08:15.000Z . This is 2022-12-13 in PT,  but because the reminders are working in UTC WedLair didn't get a training reminder on 2022-12-14.

**Comment by maramather** [comment]
I completed practice yesterday evening, did not practice during today and did not receive a reminder today. So the fix does not seem to have worked.

**Comment by maramather** [comment]
works now!
