### ISSUE TITLE
Update gray color of badges/streaks icons to be uniform

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#307]
All of the badges/streaks icons should be the same gray.  Updated icons have been attached.

[HeartBEAM award icons (gray).zip](https://github.com/EmotionCognitionLab/pvs/files/10262720/HeartBEAM.award.icons.gray.zip)

**Comment by noah10** [comment]
Per #313 there are no more streaks, so this now only applies to session icons.
