### ISSUE TITLE
Change how recall is entered for emotional memory task

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#308]
On Day 6 when the emotional memory task recall is administered, participants are asked to enter images they recall and use the mouse to submit each description.  Please change this to be similar to the Verbal Learning and Memory task where participants can hit 'enter' instead.

**Comment by noah10** [comment]
@Floozutter it looks like you could probably do this with a minor tweak to the jspsych-memory-field plugin, but please take some time to look at it in detail before changing anything. If you estimate that it's going to take more than ~2 hours then let's decide if it's worth it before you tackle it.

@cho890 If we do this it would work just like the verbal learning and memory task, with the green flash and everything. Other than the confirmation text that shows up when you click "Stop" the two would need to remain identical. Is that what you want?

**Comment by cho890** [comment]
@noah10 That sounds fine.  The confirmation message is fine for the task too, though the message should say, "Click 'OK' if you've entered all the images you remember. Click 'Cancel' if you can remember more."

The instructions on the screen should read,

"Earlier this week, you viewed and rated set of emotional pictures and rated how negative and positive each one was.  Now let’s see how many you can remember! For each picture you remember, please describe it in as much detail as possible so that someone will be able to identify the picture you describe.

For example, instead of "bird," include descriptions like "yellow bird sitting on a tree branch.”

Press the Enter key after each image description to save your response. 
Press Stop when you are done.

**Comment by noah10** [comment]
I assume the only part of the instructions above that's actually a change is the "Press the Enter key after each image description to save your response. Press Stop when you are done." bit. If any of the rest of the above is different from the existing instructions please create a separate issue for that change so that we can keep this focused on the recall entry.

**Comment by cho890** [comment]
Got it.  I believe it is different.  I will create a separate issue.

**Comment by cho890** [comment]
This has been completed.
