### ISSUE TITLE
Update instructions for emotional memory recall

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#309]
The instructions on the screen should read,

"Earlier this week, you viewed and rated set of emotional pictures and rated how negative and positive each one was. Now let’s see how many you can remember! For each picture you remember, please describe it in as much detail as possible so that someone will be able to identify the picture you describe.

For example, instead of "bird," include descriptions like "yellow bird sitting on a tree branch.”

Press the Enter key after each image description to save your response.
Press Stop when you are done.

**Comment by noah10** [comment]
OK, I've fixed those.

**Comment by cho890** [comment]
Instructions are now correct.
