### ISSUE TITLE
Add congratulatory message for achieving bonuses

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#312]
For lumosity bonuses which are paid once a week, if a participant achieves a bonus one week, display the below pop-up message when they log into the app for that day's practice:

"Congratulations! You‘ve earned a $2 bonus for improving your brain game scores this past week. Keep it up!"

For breathing bonuses which are paid each day it is achieved, display the first message below for resonance breathing condition and the second message for random paced breathing condition.

"Great job!  Your heart rate data indicate you were even more relaxed than usual during yesterday’s breathing practice. You’ve earned a $1 bonus."

"Great job!  Your heart rate data indicate you were even more alert than usual during yesterday’s breathing practice. You’ve earned a $1 bonus."

**Comment by noah10** [comment]
Having discussed this with Mara, I believe the requirements are:

- Keep track of the last date you showed a congratulation message of either type (lumosity bonus or breathing bonus) to the user
- Check the database to see what the dates of the most recent lumosity bonus and breathing bonus are
- If either (or both) of those dates are later than the last date you showed a congratulation message of that type, show the congratulation message(s) and update the last date shown information
- If neither date is later than the last date shown, do not show a congratulations message

@maramather (or @cho890 ) please update this if that is incorrect.

**Comment by maramather** [comment]
That looks correct to me.

**Comment by noah10** [comment]
If someone (in the resonance condition) happened to log in when they had gotten both bonuses, should I just show this?

> Congratulations! You‘ve earned a $2 bonus for improving your brain game scores this past week. Keep it up!
> Great job! Your heart rate data indicate you were even more relaxed than usual during yesterday’s breathing practice. You’ve earned a $1 bonus.

**Comment by maramather** [comment]
Yes, that would be fine.

**Comment by noah10** [comment]
This is now ready to test, @cho890 . I'll send you a link to the correct version of the home training app to use to test it separately.

**Comment by noah10** [comment]
While testing isn't 100% done, this is being rolled out at the same time as #344 for expedience. I'll leave this issue open for a little while longer in case anything crops up.

**Comment by cho890** [comment]
I've received correct messages for bonuses earned for several days now.  Issue is resolved.
