### ISSUE TITLE
Badges/Medals

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#313]
1. Is it possible to access this screen after leaving it?  I see it when I first log in to the app but cannot get back to it unless I quit the app and log in again.
2. Replace "Days you did everything" with "Number of days you completed home training"
3. After discussion with Mara, we have decided to remove rewards for achieving streaks.  We will only have "Number of days you completed home training".

**Comment by noah10** [comment]
1. No, this screen only shows up when you start the app.
2. Done
3. Done.
