### ISSUE TITLE
bug if user is looking at rewards when end-of-breathing-session-1 upload is occuring

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#315]
I had completed my first 15-min paced breathing session of the day, it was in the process of uploading my data when I used the menu to navigate to the rewards summary screen. I looked it over, then clicked on 'return'. It brought me to the 2nd paced-breathing session screen. I clicked on start, and it did nothing and eventually gave me an error message. I checked and emWave was not running. 

It seems that instead of requiring quitting as it usually does between sessions, if the user goes to the reward screen while the first session data is uploading, quitting is not enforced and it messes things up.

**Comment by noah10** [comment]
I think that we should just disable the earnings menu when you are on a breathing page - we really don't want users to be able to get distracted and go somewhere else when they're on that page.

**Comment by maramather** [comment]
I agree, that would work.

**Comment by noah10** [comment]
OK - once you click the "start" button (in rest breathing) or once the pacer starts running (in paced breathing) the View -> Earnings and View -> Daily Tasks menus will be disabled. They will stay disabled until you quit the app and run it again.

**Comment by maramather** [comment]
The menu was disabled as intended but it didn't appear to look any different from the other menu options (it was not greyed out as far as I could tell). If that is not possible to grey it out, that's fine, but if it is possible, that would improve the interface.

**Comment by maramather** [comment]
It is greyed out.
