### ISSUE TITLE
lower threshold for saving home breathing segments

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#322]
Please lower the threshold to be 360 coherence values for whether a segment gets saved or not.

**Comment by maramather** [comment]
per our conversation, we will wait to see if pilot testing indicates lost data is a problem.

**Comment by noah10** [comment]
So far only one participant seems to have significant problems with this. Out of the 15 reports of this in the logs between 2/14 and 2/20, 14 of them were from one participant (HepViol). 13 of those 14 cases were the final five minutes of a 10 minute session, and the lacking data ranged from just 500ms (one coherence score) to just over a minute.

**Comment by maramather** [comment]
I'm closing this issue as Noah opened another issue to address our plans to lower the threshold to 360.
