### ISSUE TITLE
error 'property 'webContents' of null

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#323]
Got a pop-up window with this error after seeing welcome screen with my username (so internet was working) and then quickly clicking on the button indicating I was done with Lumosity (without actually doing Lumosity).

other parts of the error message said

at Object.emit (events.js:327:22)
at Object.EventEmitter.emit (domain.js:467:12)

**Comment by noah10** [comment]
I suspect that this happened around https://github.com/EmotionCognitionLab/pvs/blob/main/client/src/background.js#L356 , where we try to log you in to Lumosity after the Lumosity view has finished loading. My guess is that your quickly skipping past the Lumosity section caused us to remove the Lumosity view before that line executed, leading to the view being null by the time we tried to log you in.

**Comment by maramather** [comment]
It no longer happens, thanks!
