### ISSUE TITLE
Sort Potential Participants list on admin dashboard

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#328]
Please sort the Potential Participants list on the admin dashboard by date, with oldest first.  Please delete all current data there.

**Comment by noah10** [comment]
Regarding the deletion of the data there, you're looking at dev right now. There are no potential participants in prod yet. Do you really need them deleted from dev?

**Comment by cho890** [comment]
No.  If prod is empty, then we're good.

**Comment by cho890** [comment]
This is still not sorted by date.  Here is what I see currently:

![image](https://user-images.githubusercontent.com/109320017/212163081-0d5aac80-4623-4b02-a445-41c4972c912f.png)

**Comment by noah10** [comment]
That is prod. Please use dev to test bug fixes.

**Comment by cho890** [comment]
All looks good on dev!
