### ISSUE TITLE
Do not send reminders before start date

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#331]
Participants may not start the study immediately after registering. In this case, an admin will set their start date (see #330). When a participant has a start date they should not receive any reminders until after the start date.

**Comment by choipaul92** [comment]
I have not received any notifications after changing the start date 2 days ago.

**Comment by choipaul92** [comment]
I still get reminder emails despite changing the start date to later

**Comment by choipaul92** [comment]
Update (FeySlug - paulchoi35@gmail.com) 

-After changing my start date in DEV, I did not receive any notifications ✅  
-And after changing my start date to 1/26/23 on DEV, I received a notification today at 4 PM telling me to start today ✅

 I'm assuming it was sent today due to the time zones.

**Comment by noah10** [comment]
Thanks. Though I didn't think so at first, this did turn out to be a time zone issue. I had misunderstood something about the way the time zone library I'm using works, and it was effectively assuming that a start date of "2023-01-26" had originally been set in UTC and needed to be converted to PT (which would be 2023-01-25 16:00:00, which is why you got the reminder a day early), rather than just treating it as having been set in PT. I've fixed that now, so if you can reset your start date we'll see if it works properly.
