### ISSUE TITLE
Send reminder email/message day before start of Week 1 assessments

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#334]
Below are messages to be sent to participants the day before and first day of Week 1 assessments:

--------------------------------------------------------------------

DAY BEFORE WEEK 1 ASSESSMENTS START DATE:

Hello [NAME],

This is a reminder that it's almost time to start the HeartBEAM study!  Tomorrow, please be sure to log into the HeartBEAM study website (www.heartbeamstudy.org) to start the first of 6 days of assessments.  Please complete these over 6 consecutive days.  As stated in the consent form, if you miss more than one out of 6 days of assessments, you will not be able to continue in the study.

Please let us know if you have any questions.

Best,

USC HeartBEAM Study Team

--------------------------------------------------------------------

DAY 1 OF WEEK 1 ASSESSMENTS:

Hello [NAME],

Welcome to Day 1 of the study!  We are excited that you've joined the study and look forward to seeing you in the lab soon.  

Please be sure to log into the HeartBEAM study website TODAY (www.heartbeamstudy.org) to start the first of 6 days of assessments this week.  As a reminder, these assessments should be completed over 6 consecutive days.  As stated in the consent form, if you miss more than one out of 6 days of assessments, you will not be able to continue in the study.

Please let us know if you have any questions.

--
Best,

USC HeartBEAM Study Team

**Comment by noah10** [comment]
On day 1 they'll get the regular reminder, so I'd recommend dropping the special one that day. Also, it looks like this is just supposed to go out via email, not SMS? If we do want an SMS version please provide the text for that.

**Comment by cho890** [comment]
Ok, great.  The day before one is fine.  What is the limitations of text messages?

**Comment by noah10** [comment]
A text message should be 140 characters or less. Please don't use a URL shortener like bit.ly - apparently that tends to trigger spam filters and could result in the message not being delivered.

**Comment by cho890** [comment]
Here is the text message:

It's almost time to start the HeartBEAM study! Log in tomorrow at [www.heartbeamstudy.org](http://www.heartbeamstudy.org/) to complete Day 1 of 6 days of assessments.

**Comment by noah10** [comment]
What time should this go out?

**Comment by cho890** [comment]
10AM sounds good to me.

**Comment by noah10** [comment]
What should the subject line for the email be? Also, I'm going to drop the personalization (first name) from the message as the infrastructure I have set up to do all of the others doesn't include it.

**Comment by noah10** [comment]
Also, do we want to hit them with email and SMS simultaneously at 10AM, or do we want the two channels to go out at two different times?

**Comment by cho890** [comment]
How about the below as the subject?  Both going out at the same time seems fine to me unless you have other thoughts.

Reminder:  Start the HeartBEAM Study Tomorrow!

**Comment by noah10** [comment]
OK - this is out on dev and ready to be tested.

**Comment by cho890** [comment]
I scheduled 2 reminder messages to be sent out and both were received.  Can we make a minor update to the language using the below text?  This issue is then ready to be closed.
----------------------------------------
Hello,

Thank you so much again for joining the USC HeartBEAM Study!  This is a friendly reminder that you are starting the study tomorrow. You will receive an email tomorrow with a link to log in to the study website (www.heartbeamstudy.org) to complete the first of 6 days of assessments. Please complete these over 6 consecutive days. As stated in the consent form, if you miss more than one out of 6 days of assessments, you will not be able to continue in the study.

Note:  These assessments are designed to be challenging, so please do not worry if you find some of them difficult!  We only ask that you do the best you can. :)  Please let us know if you have any questions.

Best,

USC HeartBEAM Study Team
