### ISSUE TITLE
Use start date when determining pre-baseline status

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#338]
Right now the pre-baseline status will show red for all users who have done no sets, even if their start date is in the future. It should show gray until the start date, and then determine status based on the number of sets done and the number of days since the start date following the same algorithm as the current code. If the start date is not set the account creation date should be used instead.

**Comment by noah10** [comment]
This is ready to be tested on the dev dashboard.

**Comment by cho890** [comment]
This looks to be completed.
