### ISSUE TITLE
Don't allow users to begin cognitive baseline before their start date

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#339]
We have at least one user who said he was going to start on a given date and then started well before that. This is problematic because the cognitive baseline needs to be done in as close to six consecutive days as possible so that users don't have vastly different amounts of time between the learning and recall phases of tasks that span multiple days. We need to prevent users from doing the cognitive baseline before their start date and display a message telling them to come back on their start date.

**Comment by choipaul92** [comment]
Update: 

-I received the email on my start date (today)
-I received my reminder email at 6 AM today and 4 AM (don't forget to do the brain challenges every day with the dev link). 
-I did not receive any emails on Friday

**Comment by choipaul92** [comment]
Tested: All Good ✅ 

-Changed the start date to months later: cannot access cog baseline
-Changed the start date to the past: can access cog baseline 
-Changed the start date to today: can access cog baseline
