### ISSUE TITLE
participants in random condition may fail to get regimes for breathing

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#344]
At [https://github.com/EmotionCognitionLab/pvs/blob/ebf85cbf2bde9264bd574d0214f10c82467627d6/client/src/regimes.js#L230](https://github.com/EmotionCognitionLab/pvs/blob/ebf85cbf2bde9264bd574d0214f10c82467627d6/client/src/regimes.js#L228), we're in a rare state where there are no regimes whose 90% CI bounds overlap the target average coherence. In this case we're just supposed to pick the regime whose average coherence is closest to the target average coherence. Unfortunately, [we try to do that](https://github.com/EmotionCognitionLab/pvs/blob/ebf85cbf2bde9264bd574d0214f10c82467627d6/client/src/regimes.js#L230) using the wrong key (avg_coherence, rather than mean), making our attempt futile and generating an error.

**Comment by choipaul92** [comment]
Tested and Breathing Practice Worked after Deleting old Heartbeam and Reinstalling new Heartbeam!
