### ISSUE TITLE
make verbal-fluency work for post-intervention baseline

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#345]
The verbal-fluency task has five letters and once you've done them all (across five sets) you can't do any more. In the post-intervention baseline we have to make sure we ignore the letters the participant did in the pre-intervention baseline.

**Comment by noah10** [comment]
This is ready to be tested, but testing it is a little tricky - you have to do the verbal-fluency task for every set in the pre-intervention baseline and in the post-intervention baseline. To do that without the time and tedium of doing the entire pre- and post-intervention baselines, follow these instructions:

1. Open a new browser window
2. Right-click in the window and choose "Inspect"
3. Click the "Console" tab in the panel that opens
4. In that window, go to https://dev.heartbeamstudy.org/daily-tasks/?tasks=verbal-fluency&setNum=1
5. Write down the letter that you assigned to use
6. Repeat steps 4 and 5 using 2, 3, 4, and 6 as the setNum 
7. Repeat step 4 using 5 as the setNum. In the console tab you should see an error that says "All of the verbal fluency tasks have been completed."
8. Check the list of letters you wrote down and verify that you never saw a given letter more than once

Now you're ready to test the post-intervention sets:
1. Repeat steps 4 and 5 using 7, 8, 9, 10, and 12 as the setNum 
2. Repeat step 4 using 11 as the setNum. In the console tab you should see an error that says "All of the verbal fluency tasks have been completed."
3. Check the list of letters you wrote down for the post-intervention steps and verify that you never saw a given letter more than once

**Comment by maramather** [comment]
@cho890 would you decide who to assign this to? Either Paul or Juliana perhaps?

**Comment by juliana-20** [comment]
Verbal fluency task has been tested for both pre- and post-interventions. Everything looks good – no repeated letters and error msg appears where it correctly needs to.

**Comment by noah10** [comment]
Great - I've deployed this to production.
