### ISSUE TITLE
move demographics to the start of Set 1

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#347]
Please move demographics to the start of Set 1 (it is currently administered on Set 2).

**Comment by noah10** [comment]
This is ready to test on dev. Note that to test it you will either need an account that has never done any part of the cognitive baseline or to delete all of the cognitive baseline data from an account and use that.

**Comment by nashiro** [comment]
I plan to ask Juliana to test it she hasn't done any part of the cognitive baseline. Is this the right link she should go to: https://dev.heartbeamstudy.org/daily-tasks/index.html ?

**Comment by noah10** [comment]
That's correct. Please check with Alex first, though - it's possible that she has already tested this as part of testing #348 .

**Comment by noah10** [comment]
@ycazaherrera reports that this is working. Closing.
