### ISSUE TITLE
Remove n-back from Set 1; move first day with training to set 2; complete for pre and post

### ISSUE THREAD

**Issue by ycazaherrera** [EmotionCognitionLab/pvs#348]
Please remove the n-back from set 2. Please move the n-back task with the full training that is currently viewed during set 1 to set 2. The existing shorter version without the full training will remain in effect for sets 3-6. The n-back specs doc has been updated to reflect the changes in which sets the task is completed and what version is viewed each day. Please do this for the pre and post sets.

**Comment by noah10** [comment]
This is ready to be tested on dev. Note that to test it you will need an account that has done no cognitive baseline tasks, or to delete all of the cognitive baseline data from an existing account.

**Comment by maramather** [comment]
Alex and Padideh have tested the pre-intervention sets. Padideh is still planning on testing Set 7, but I am going to close this issue so that Noah can install the update before the next wave of 4 participants start their baseline assessments.
