### ISSUE TITLE
change the message of the automated emails/SMS for stage 3

### ISSUE THREAD

**Issue by HyunjooY** [EmotionCognitionLab/pvs#349]
Hi Noah,

As we discussed via slack, would you change the text of the automated emails/SMS for stage 3?
This is for a reminder participants need to increase breathing practice time (from one to two) when they start stage 3. 
Below is the message for stage 3. Thank you!

    subject: "A quick reminder to train today!",
    html: "Have you done your training today? Remember to play brain games and complete two 15-minute paced breathing exercises today!",
    text: "Have you done your training today? Remember to play brain games and complete two 15-minute paced breathing exercises today!",
    sms: "Have you done your training today? Remember to play brain games and complete two 15-minute paced breathing exercises today!"

**Comment by noah10** [comment]
@HyunjooY  - Looking at the code I realized that when somebody has done no breathing segments for the day there's no easy way to know what stage they are in. (I could pull historical breathing data, but that can end up being a lot of data, which could slow things down, so I'm trying to avoid that.)

Is it OK if this message only goes out to someone who has already done at least one breathing segment for the day, and the old message goes out otherwise? Because the home training reminder goes out 2x/day (at 11AM and 7:30PM) that would still catch people who did one 15 minute session. (At least if they did it before 7:30PM - if they didn't they'd still get the old message at 7:30PM.)

**Comment by HyunjooY** [comment]
It would be fine with me. Thank you!

**Comment by noah10** [comment]
This is up on dev and ready to be tested. @HyunjooY , if your account on dev isn't in stage 3 let me know if you'd like me to manipulate the data to put it into stage 3.

**Comment by HyunjooY** [comment]
Okay. My account is in stage 3.
So, for testing, I need to do one practice before 7:30 PM, right?
I returned all the lab devices so is it okay to install the dev version on one of my windows laptop and practice it?
I guess I need to do this with a new laptop; go to View->Toggle Developer Tools, click the "Application" tab in the window that appears, click Local Storage on the left and click app://. Then create a key named "HeartBeam.isConfigured" with the value "true"
If you prefer I use the lab laptops, I will test it tomorrow.

**Comment by noah10** [comment]
Yes, just do one 15-minute session before 7:30PM. And yes, it's fine to install a dev version on your own laptop and you have the correct steps there. You may end up seeing a video (or double videos) that you've seen before, but just ignore that.

**Comment by HyunjooY** [comment]
I did one 15 min session now; I will let you know which message will be delivered at 7:30 PM.

**Comment by HyunjooY** [comment]
I did not get 7:30 PM message. I only got the 6 AM message today. Actually I have gotten 6 AM and 4 PM messages for a few weeks.
I did not do lumosity game. Is it the reason?
This is my email folder screenshot.
<img width="1563" alt="image" src="https://user-images.githubusercontent.com/41126740/224083622-73de7b96-6d73-4c64-845a-4812959bfb1c.png">

**Comment by noah10** [comment]
Ah - that tells me that you haven't finished the pre-intervention baseline yet, so you get reminders for that, not for the home training practice. Slack me the email address you're registered with on dev and I'll mark your account as having finished the baseline.

**Comment by HyunjooY** [comment]
I got this message at 11 am. It looks good. 
<img width="1559" alt="image" src="https://user-images.githubusercontent.com/41126740/224135411-f29294cb-183f-41c0-9c72-e251e942ae1f.png">

**Comment by noah10** [comment]
This has been deployed to production.
