### ISSUE TITLE
baseline reminders

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#359]
Please turn off baseline reminders when they have completed all 6 sets (as it does currently). Also, when Visit 2 is marked as complete, turn off baseline reminders if they have not yet completed all 6 sets.

**Comment by noah10** [comment]
Note: If an admin *unchecks* visit 2 we will then need to see if the user has finished all six sets to determine if we should set preComplete to false or not.

**Comment by noah10** [comment]
This is complete and deployed to production.
