### ISSUE TITLE
Daily Stressors is missing a question

### ISSUE THREAD

**Issue by andyjkim628** [EmotionCognitionLab/pvs#36]
This question was present in the SPECS but not in the task: What do you feel your stress level is today on a scale from 1 to 9 (1 = very low, 5 = moderate, 9 = very high)? ___________

**Comment by noah10** [comment]
Good catch. Assigning to David to fix this.

**Comment by noah10** [comment]
This has been fixed. Please test (remembering to shift-reload to ensure your browser has the latest version of the experiment) and close the issue if the change is as requested.
