### ISSUE TITLE
Change Reminder Email Address to another Email Address

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#360]
Currently, participants are receiving and responding to emails from and to usc..lab@gmail.com. No one is checking usc...lab gmail account; can we change it so that the reminder emails are coming from usc...eam@gmail.com?

**Comment by noah10** [comment]
Unfortunately this is not easy to do and could result in recipients not getting reminders. I would recommend that you instead simply set up the unchecked email address to forward all of its mail to the checked address.
