### ISSUE TITLE
Remove 'x' as a response option in emotional memory task

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#364]
This applies to the encoding part of the task administered in both sets 4 and 10.  On the instruction screen, please remove "If you did not see the picture, please press ‘x’”.  Please also remove 'x' to be a response option that participants can provide.

**Comment by noah10** [comment]
This is up on dev and ready to be tested.

**Comment by cho890** [comment]
This issue has been completed.
