### ISSUE TITLE
avoiding super slow breathing paces

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#367]
We found a user that is hitting our limits in terms of how slow the pacing should be.

Change the code so that we don't assign paces that are set in 'validateRegimeBreathPacer' 

When the app would otherwise be selecting something outside of the limit, assign the person to the pace that is at the limit.

**Comment by maramather** [comment]
I've done some reading on slow yogic breathing and think it would be fine to move the slow limit to be 1 breath/min. But we should still include the back-stop specified above if that limit is reached (i.e., when the app would otherwise be selecting something outside of the limit, assign the person to the pace that is at the limit.)

**Comment by noah10** [comment]
A production build (v2.0.6) with this change has been made available for future participants.
