### ISSUE TITLE
Replace fixation cross in n-back

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#368]
To avoid repeated participant confusion regarding having to do addition, please replace the fixation cross in the N-back task with the option-8 dot: •

**Comment by noah10** [comment]
This has been deployed to dev and is ready for testing.

**Comment by choipaul92** [comment]
Tested and can confirm that the cross fixations are dots.

**Comment by noah10** [comment]
This has been deployed to production.
