### ISSUE TITLE
Add "lab visit 4" breathing option

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#371]
We would like participants (existing and new) to do a five-minute breathing segment during their 4th lab visit. The segment should follow a breathing regime that they would ordinarily do. If they have already done all of their breathing for the day when they visit the lab it's OK for them to repeat a segment they have already done. If they have not yet done Lumosity for the day when they arrive they should not be required to do it before doing this breathing segment. If they have not yet completed their breathing for the day this segment can should count as one of their segments for the day (even if it is done before Lumosity). Note that they *should* be required to do Lumosity before continuing on to any of their other breathing segments for the day.

Looking at the code it doesn't appear as if this should affect payment at all. If it does cause a modest extra payment that it is acceptable; it is not acceptable if it somehow causes their payment to be reduced (unlikely).

This will be integrated into the regular app. Participants will bring their own laptops and sensors with them and do the training on those. It is important that participants not be able to access this "lab visit 4" breathing mode at home; starting it should either be done via a hidden key combo by the researcher or by a password entered by the researcher.

We should upload the user data when this finishes, as the participant may only be one day away from finishing the experiment and could conceivably not do any further breathing practice after this, meaning there wouldn't be any more uploads.

**Comment by maramather** [comment]
this all sounds correct. Thanks!

**Comment by noah10** [comment]
This has been deployed to production.
