### ISSUE TITLE
Mind-in-Eyes task, glossary updated.

### ISSUE THREAD

**Issue by HyunjooY** [EmotionCognitionLab/pvs#41]
The original glossary document has three missing words (bored, shy, excited). We decided to add them.
I updated the glossary documents. Could you update the task using the updated glossary document?
Thank you!

**Comment by noah10** [comment]
OK - I've updated the glossary with these words. If the fix looks good to you please go ahead and close this issue.

**Comment by HyunjooY** [comment]
I tested again and still I can see only word not found message for "bored". Sorry. Something I missed?

**Comment by noah10** [comment]
Heh - no, just didn't expect you to test it that quickly. :-) It can take a while for the new code to show up, so when you tested so soon you got the old code. I went ahead and forced the server to start serving the new stuff now, though, so if you test again (at least in the solo task - maybe not as part of the daily tasks) you should see the new code.

**Comment by HyunjooY** [comment]
Ah..sorry...sometimes I need more patience...
Anyway now it worked well! Thank you for working on this. I will close this one.
