### ISSUE TITLE
color scheme could be easier on the eyes

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#43]
The white background/black text scheme that we have now could be tough on the eyes when you have to sit in front of it for 45-60 minutes without a break. We should come up with a new scheme that is sufficiently high contrast that it doesn't significantly diminish readability (compared to black on white) but is easier on the eyes.

**Comment by ycazaherrera** [comment]
Please change the color scheme to beige background with black text. 

The team was shown screenshots of multiple background-text color combos and beige background with black text received the most votes (at least by those that voted).

**Comment by noah10** [comment]
This should now be done, with a few caveats: 

- backgrounds of photos (in face-name and pattern-separation, for example) will not be changed - it would be a lot of effort and the results would probably not be very good
- the background of the objects in spatial-orientation will not be changed (they became difficult to see when we tried it out)

**Comment by ycazaherrera** [comment]
Thanks! Anya and I will check them out. I think she is going to do 5 days of daily tasks starting on Sunday, so I will make sure to get feedback from her about how it all looks/feels when done in a longer block.

**Comment by anyavincent** [comment]
The beige background looks much better and is much easier on the eyes! One issue that I ran into is that when scrolling through the questionnaires, the beige background changes to white when scrolling down to parts that do not initially show. I have attached a picture that should show what I mea
<img width="1440" alt="Screen Shot 2021-10-05 at 8 28 01 AM" src="https://user-images.githubusercontent.com/89997156/136078497-1bc4a18e-c388-404c-9234-581777140a38.png">

**Comment by noah10** [comment]
That's odd. What browser and operating system are you seeing this in? And it looks like you're seeing this in full-screen mode, is that correct? And does it ever switch to beige, for example if you scroll around?

**Comment by anyavincent** [comment]
I was using safari on macOS Big Sur Version 11.6. I was in full screen mode, and it only switches back to beige if I scroll back up to what was originally shown on the full screen.

**Comment by noah10** [comment]
This particular problem has been opened separately as #126, so I'm going to close this issue since the main color scheme change is done.
