### ISSUE TITLE
Daily Stressors - minor edits needed

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#47]
1. Please changes "Read each question and choose the appropriate answer" to "Please read each question and choose the appropriate answer about recent stressful events"
2. Q7: Since (this time yesterday, did anything happen to a close friend... --> remove a parenthesis (i.e. Since this time yesterday, did you..)
2. last question: since (this time/we spoke) yesterday --> since this time yesterday

Link to the spec
https://docs.google.com/document/d/1TwBqm_vJ0naQ7nybcfkXbU_WZsrlGIOdttiM7sN8A5Y/edit

**Comment by noah10** [comment]
This has been fixed. Please test (remembering to shift-reload) and close the issue if the change is as requested.
