### ISSUE TITLE
PANAS - minor edits needed

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#48]
Please change the instructions to:
"This questionnaire consists of a number of words that describe different feelings and emotions. Please read each item and then mark the appropriate answer. Indicate to what extent you feel this way right now, that is, at the present moment."

Link to the spec
https://docs.google.com/document/d/1-2O9viWjQJdyMhiA-iBbPTaO68-719SXjrWLJbdqhOE/edit

**Comment by noah10** [comment]
This has been fixed. Please test (remembering to shift-reload) and close the issue if the change is as requested.

**Comment by nashiro** [comment]
I can't see the changes.  Is it possible that the changes are not uploaded yet?

I was able to see changes you made in other questionnaires (i.e., Daily Stressor and Face-Name) using Safari.  "Shift-reload" didn't work using google chrome or safari.

**Comment by noah10** [comment]
That's very odd. Can you try it in a private (or incognito) window and see what happens? I'm quite surprised that shift-reload isn't bringing it up; that should force your browser to ignore what you have cached and fetch it again from the server.

**Comment by nashiro** [comment]
Paul tried it too but it looks like he also doesn't see the changes:
He says, "For MAC, safari and chrome shows: “This questionnaire consists of a number of words that describe different feelings and emotions. Read each item and then mark the appropriate answer in the space next to that word. Indicate to what extent you feel this way right now, that is, at the present moment. Use the following scale to record your answers.” For Windows, its the same (for chrome and microsoft edge)"

I just tried incognito on Safari and Chrome but still don't see the changes...
I can ask other team members to try it out if that helps.

**Comment by noah10** [comment]
OK - I think what you're saying is "I (or least Paul) see the changes, but they aren't exactly to spec." 

The original:

> Read each item and then choose the appropriate answer. 
> Indicate to what extent you feel this way right now, that is, at the present moment. 

What we have now:
 > This questionnaire consists of a number of words that describe different feelings and emotions. Read each item and then mark the appropriate answer in the space next to that word. Indicate to what extent you feel this way right now, that is, at the present moment. Use the following scale to record your answers.

What [you asked for](https://github.com/EmotionCognitionLab/pvs/issues/48#issue-988330999):
> This questionnaire consists of a number of words that describe different feelings and emotions. Please read each item and then mark the appropriate answer. Indicate to what extent you feel this way right now, that is, at the present moment.

So it looks like the first sentence is good, the second needs to start with the word "Please" and should drop "in the space next to that word" from the end, the third sentence is good and the fourth sentence should be dropped. Is that right?

**Comment by nashiro** [comment]
Yes! thank you

**Comment by noah10** [comment]
Nope. Reassigning to @Floozutter for those final tweaks.

**Comment by Floozutter** [comment]
Sorry about that! I copied
> This questionnaire consists of a number of words that describe different feelings and emotions. Read each item and then mark the appropriate answer in the space next to that word. Indicate to what extent you feel this way right now, that is, at the present moment. Use the following scale to record your answers.
off the [spec](https://docs.google.com/document/d/1-2O9viWjQJdyMhiA-iBbPTaO68-719SXjrWLJbdqhOE/view) without realizing that it differed from the [issue](https://github.com/EmotionCognitionLab/pvs/issues/48#issue-988330999).

Could the specification document be updated to reflect the change?

**Comment by nashiro** [comment]
Hi David - Te spec was updated.  I'm not sure if it is confusing because I used track changes? If so, I'll accept them - please let me know. 
![Screen Shot 2021-09-13 at 9 56 09 AM](https://user-images.githubusercontent.com/26439818/133125666-da160ad5-6142-4c26-b920-f9976c2cb73d.png)

**Comment by noah10** [comment]
I think the culprit here is that track changes doesn't show up if you view the spec when you're not logged in. Given that, it's probably best *not* to use track changes (contrary to what I said before) in order to avoid confusion. If we need to check when/whether something was edited we can always look at version history. (And yes, please go ahead and accept the changes so that they show up for everyone, logged in or not.)
![Screen Shot 2021-09-13 at 2 10 13 PM](https://user-images.githubusercontent.com/399541/133157013-855a3c54-f845-46bc-87d3-9392334155f7.png)

**Comment by nashiro** [comment]
Sure - I accepted the changes.

**Comment by noah10** [comment]
OK - these changes should now be deployed. Please test and close this issue if it looks like everything requested is there.

**Comment by nashiro** [comment]
All looks good - thank you!
