### ISSUE TITLE
Face-Name task needs editing

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#49]
Please make the following changes:
1. Hit spacebar to advance to next face-name pair during encoding --> Show each face-name pair for 5 sec (i.e. not self-paced)
2. For the recall trials, the "1. X 2.Y" options are too close together --> Increase the gap
3. The name presentation starts just slightly before the picture is presented. Almost like a subliminal flash in the location of the picture once loaded (comment from Alex). I had the same issue; however, it only happened when I first tested the task but didn't happen during my subsequent testing. 
4. Instructions at the beginning: "In this task, you will be asked to view face-name pairs twice and remember them for a later memory test." -->  "In this task, you will be asked to view face-name pairs twice and remember them for a later memory test (today and on subsequent days).
6. Instructions just before the actual encoding task: "We will begin the actual task. You will see 8 new face-name pairs." --> "We will begin the actual task. You will see 8 new face-name pairs. Please try to remember them for a later memory test (today and on subsequent days)."
7. Paul commented: is the wording “8 face name pairs” confusing? Should we consider a different type of wording? --> I don't have a great idea for this. Any suggestions would be appreciated. 

Link to the spec:
https://docs.google.com/document/d/1DAMpzbQqP0jyV3miM-n7yCgt3UTRrqXb-w6yLo3pXcA/edit

**Comment by noah10** [comment]
How about "You will see pictures of people along with their names"? (Or, if we absolutely must say how many they will see, "You will see pictures of 8 people along with their names".)

**Comment by nashiro** [comment]
"You will see pictures of people along with their names"?  sounds good - thank you!

Also would you mind adding the following (noted in the spec)?
1. During encoding, present “Read out and memorize” above a face.
2. During tests, Present “What is the person’s name?” above a face.
![Face-Name Task](https://user-images.githubusercontent.com/26439818/132107269-03e5631c-6eae-4aeb-9a26-04facf37ad1d.png)

**Comment by noah10** [comment]
"Read out" is a bit weird. Do you want them to read it out loud? If so, I'd recommend "Read out loud and memorize". If not then just "Read and memorize".

**Comment by noah10** [comment]
And for consistency, I'd recommend the following changes for 4 and and 5 above:

4. Instructions at the beginning: "In this task, you will be asked to view face-name pairs twice and remember them for a later memory test." --> "In this task, you will see pictures of people along with their names and be asked to remember them for a later memory test. You will see each face-name pair twice. You will need to remember them today and on subsequent days.
5. Instructions just before the actual encoding task: "We will begin the actual task. You will see 8 new face-name pairs." --> "We will begin the actual task. You will see pictures of people along with their names. Please try to remember them for memory tests that will happen later today and on subsequent days."

**Comment by noah10** [comment]
@nashiro - are my suggested edits above all OK?

**Comment by nashiro** [comment]
Yes your suggested edits look great. thank you!

**Comment by noah10** [comment]
I believe these have now all been addressed. Please give it a try and close this issue if all the changes are as requested.

**Comment by nashiro** [comment]
The changes don't seem to be reflected in the link below. Should I try a different link?
https://dev.heartbeamstudy.org/index.html

**Comment by noah10** [comment]
You may need to click on the face-name link and then, after the page has loaded, hold down the shift key and click the reload button in order to force your browser to load the latest version. In general you'll always want to shift-reload whenever you're testing a change in order to ensure you're looking at an up-to-date version.
