### ISSUE TITLE
Verbal learning memory task: one word (giraffe) from first list less intelligible

### ISSUE THREAD

**Issue by mjDahl** [EmotionCognitionLab/pvs#61]
Dear Noah & David,
I found one word (giraffe) of the first list of the verbal learning and memory task (CVLT) less intelligible than the other ones. It could be me, but if native speakers have a similar impression we could consider re-recording the word?
Best,
Martin

**Comment by noah10** [comment]
For my part I didn't find it unintelligible. Maybe you could poll the native English-speaking lab members on Slack and see what their thoughts are?

**Comment by mjDahl** [comment]
I am happy to go with your assessment in this regard. Plus, thinking more about this, re-recording a single word may induce even greater differences
