### ISSUE TITLE
Minor issue on the Pattern separation task 

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#62]
Padideh's RA, Meghan, tried the Pattern Separation Task and reported below:

When her browser was zoomed in at 100%, the screen looked like this (the first attachment) and she couldn't see the question or answer options.

But when she zoomed out to ~ 80%, the screen looked like this (the second attachment) and she was able to see the question. She used chrome and her laptop is Macbook Pro 2015, 13-inch.

Is this something you could fix (i.e., the question or answer options will always appear regardless of zoom setting)?

![Image from iOS](https://user-images.githubusercontent.com/26439818/134560184-e186f705-e6d2-45f8-998c-4d9c94eb7e0b.jpg)
![Image from iOS (1)](https://user-images.githubusercontent.com/26439818/134560214-7d757108-5676-4eb9-ba28-9aac41abf9c7.jpg)

**Comment by noah10** [comment]
That's very odd. In real life everybody will be doing this in full-screen mode, so we should check that. @arielle68, could you have your RA try this in full screen mode (View -> Enter Full Screen) and see if the problem still exists there?

**Comment by arielle68** [comment]
She said she can see the questions in full screen mode

**Comment by noah10** [comment]
OK - I'm going to close this, then. We can re-open it if the issue shows up on full-screen in the future. (We'll also be changing the size of the photos to address #33, which could affect this.)
