### ISSUE TITLE
N-Back Task: Font Size 

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#89]
I noticed when doing the N-back Task that the font size was a bit small for instructions and the number. Do you guys think it would be good if we increased the size?

**Comment by noah10** [comment]
I believe the font size for the instructions is the same as the font size everywhere else. @Floozutter, could you double-check that? If it's different please make it the same.

**Comment by Floozutter** [comment]
Yup, the font size of the n-back instruction text is indeed normal. If the cue font size(s) or the n-back trial font size should be increased, please let me know.

**Comment by choipaul92** [comment]
I think a bigger font size for the numbers for the n-back would be good; would love to hear feedback from others?

**Comment by noah10** [comment]
Personally I'd rather keep things consistent, but @ycazaherrera this is really up to you.

**Comment by ycazaherrera** [comment]
I see what Paul means - it wouldn't hurt to increase the size. However, I do not think it is a necessity. I think the font size can remain consistent using the bolded format already in use for the numbers.
