### ISSUE TITLE
Spatial Orientation Task: Instructions 

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#90]
While doing the task clarified what I had to do, the instructions were difficult to understand. Also, should we put the last paragraph [a/o the example] on a second page so that it isn't too long (the "press the spacebar to continue" was cut off).

**Comment by noah10** [comment]
@Floozutter - could you please make the necessary change to make sure that the "press the space bar..." instruction isn't cut off? And maybe just let Hyun Joo know that Paul found the instructions difficult to understand - if she wants to change them we can open a separate issue for that.

**Comment by noah10** [comment]
This is up and ready to test.

**Comment by HyunjooY** [comment]
Sorry. I did not know this issue is opened so I opened another issue https://github.com/EmotionCognitionLab/pvs/issues/153#issue-1060407868.

**Comment by noah10** [comment]
No worries - I actually wanted a separate issue opened if we were going to change the instructions, so that's perfect. @choipaul92 , can you please test this and close it if the second page no longer cuts off the "press space bar to continue" instruction?
