### ISSUE TITLE
2-back instructions

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#97]
<img width="2048" alt="2-back instructions" src="https://user-images.githubusercontent.com/26439818/140592950-34c56ceb-4853-4f3e-80a9-78cb9a834627.png">

I tested the N-back task individually and noticed that the instructions for the 2-back task may be incorrect? It looks like the instruction for the 1-back task. Could you double check?

**Comment by noah10** [comment]
It looks like you're right. @Floozutter, could you please correct that?

**Comment by Floozutter** [comment]
@nashiro Thanks for catching that! Once #104 is up, that screen should look like this:
![fixed-ti2a](https://user-images.githubusercontent.com/57658864/140965552-a62e846b-5acb-4553-a84a-49936bad6945.png)

**Comment by noah10** [comment]
This is up and ready to test.

**Comment by nashiro** [comment]
I tested it and it was fixed. thank you
