### ISSUE TITLE
Demographic Information needs editing

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#98]
1) "Are you currently under a doctor’s care for any of the following? Indicate if yes, otherwise leave blank"
Please edit the response options as follows:

Heart disease (including coronary artery disease, angina, and arrhythmia)
Vascular disease
Diabetes  (If yes, ____Type I,   or _____Type II,   or _____Pre-diabetes)
None of them

Please type everything shown above including the text in parentheses.
Please add another response option: None of them  

2)  Have you ever been diagnosed with a psychiatric disorder?   
Please add:
If “yes”, specify: _____________________________________________

3) Are you currently taking any medications/drugs for any of the following? (including over-the-counter drug, alternative remedy and prescription medication.)
Please add another response option: None of above

**Comment by noah10** [comment]
I'm going to break this up into separate issues because there are several different things going on here. The sub-information about diabetes and psychiatric disorders already exists - you have to indicate that you have diabetes or a psychiatric disorder in order to see them - so I won't create issues for those.

**Comment by noah10** [comment]
The change for the heart disease text is #122 and the change to add the "None" options and force users to choose an option in the "doctor's care" and "medications/drugs" sections is #123. Please go to those issues and set up notifications for them; I'm closing this one.
